"""Market Context lane — entity resolution, event clustering, baseline sentiment, extraction, expectations."""

from .entity_resolution import (
    PRODUCER_VERSION as ENTITY_RESOLUTION_VERSION,
    ContextDocumentRecord,
    build_symbol_mapping_registry,
    load_context_document_records,
    raw_document_from_fixture_row,
    resolve_document_entities,
    resolve_entity_from_claims,
)
from .event_clustering import (
    cluster_fixture_records,
    cluster_information_events,
)
from .extraction import (
    PRODUCER_VERSION as EXTRACTION_VERSION,
    DocumentExtractionResult,
    EventExtractionSummary,
    LlmExtractionLabel,
    build_event_extraction_summaries,
    build_fixture_extraction_pipeline,
    document_extraction_to_dict,
    enrich_events_with_extraction,
    enrich_information_event,
    event_extraction_summary_to_dict,
    extract_document,
    extract_metrics_rule_v1,
    infer_economic_channels,
    load_llm_extraction_fixture,
    load_structured_metrics_fixture,
    map_canonical_event_type,
)
from .expectations import (
    PRODUCER_VERSION as EXPECTATIONS_VERSION,
    build_fixture_surprise_pipeline,
    build_surprise_cross_lane_evidence,
    load_expectations_fixture,
    surprise_summary_to_dict,
)
from .impact_components import (
    PRODUCER_VERSION as IMPACT_COMPONENTS_VERSION,
    build_fixture_impact_pipeline,
    build_impact_cross_lane_evidence,
    impact_component_summary_to_dict,
)
from .catalyst import (
    PRODUCER_VERSION as CATALYST_VERSION,
    build_catalyst_cross_lane_evidence,
    build_fixture_catalyst_pipeline,
    catalyst_summary_to_adapter_row,
    catalyst_summary_to_dict,
    short_thesis_invalidation_to_dict,
)
from .attention import (
    PRODUCER_VERSION as ATTENTION_VERSION,
    build_attention_cross_lane_evidence,
    build_fixture_attention_pipeline,
    attention_summary_to_adapter_row,
    attention_summary_to_dict,
)
from .information_decay import (
    PRODUCER_VERSION as INFORMATION_DECAY_VERSION,
    build_fixture_information_decay_pipeline,
    information_decay_summary_to_dict,
)
from .author_intelligence import (
    PRODUCER_VERSION as AUTHOR_INTELLIGENCE_VERSION,
    build_author_intelligence_cross_lane_evidence,
    build_fixture_author_intelligence_pipeline,
    author_intelligence_summary_to_dict,
    load_social_author_fixture,
)
from .sentiment import (
    PRODUCER_VERSION as SENTIMENT_VERSION,
    DocumentSentimentResult,
    EventSentimentSummary,
    aggregate_event_sentiment,
    build_event_sentiment_summaries,
    build_fixture_sentiment_pipeline,
    build_sentiment_cross_lane_evidence,
    load_finbert_fixture_labels,
    score_document_sentiment,
    score_keyword_baseline,
)

__all__ = [
    "ENTITY_RESOLUTION_VERSION",
    "EXPECTATIONS_VERSION",
    "EXTRACTION_VERSION",
    "IMPACT_COMPONENTS_VERSION",
    "SENTIMENT_VERSION",
    "CATALYST_VERSION",
    "ATTENTION_VERSION",
    "AUTHOR_INTELLIGENCE_VERSION",
    "INFORMATION_DECAY_VERSION",
    "ContextDocumentRecord",
    "DocumentExtractionResult",
    "DocumentSentimentResult",
    "EventExtractionSummary",
    "EventSentimentSummary",
    "LlmExtractionLabel",
    "aggregate_event_sentiment",
    "build_event_extraction_summaries",
    "build_event_sentiment_summaries",
    "build_fixture_catalyst_pipeline",
    "build_fixture_attention_pipeline",
    "build_fixture_extraction_pipeline",
    "build_catalyst_cross_lane_evidence",
    "build_attention_cross_lane_evidence",
    "build_author_intelligence_cross_lane_evidence",
    "build_fixture_author_intelligence_pipeline",
    "build_fixture_impact_pipeline",
    "build_fixture_sentiment_pipeline",
    "build_fixture_surprise_pipeline",
    "build_impact_cross_lane_evidence",
    "build_sentiment_cross_lane_evidence",
    "build_surprise_cross_lane_evidence",
    "build_symbol_mapping_registry",
    "cluster_fixture_records",
    "cluster_information_events",
    "catalyst_summary_to_adapter_row",
    "catalyst_summary_to_dict",
    "attention_summary_to_adapter_row",
    "attention_summary_to_dict",
    "document_extraction_to_dict",
    "enrich_events_with_extraction",
    "enrich_information_event",
    "event_extraction_summary_to_dict",
    "extract_document",
    "extract_metrics_rule_v1",
    "impact_component_summary_to_dict",
    "infer_economic_channels",
    "load_context_document_records",
    "load_expectations_fixture",
    "load_finbert_fixture_labels",
    "load_llm_extraction_fixture",
    "load_structured_metrics_fixture",
    "load_social_author_fixture",
    "author_intelligence_summary_to_dict",
    "map_canonical_event_type",
    "raw_document_from_fixture_row",
    "resolve_document_entities",
    "resolve_entity_from_claims",
    "score_document_sentiment",
    "score_keyword_baseline",
    "short_thesis_invalidation_to_dict",
    "surprise_summary_to_dict",
]
