"""Item 9 validation-readiness shared vocabulary (no fitting).

Companion tokens for readiness snapshot, calibration preflight, methodology
freeze, and Paper acceptance. Binds to protocol ``item9.calibration-protocol/1.0.0``
without bumping that protocol into a fittable revision.
"""

from __future__ import annotations

from typing import Final

from .item9_calibration_protocol import PROTOCOL_VERSION

# ---------------------------------------------------------------------------
# Schema / artifact ids (companions; protocol stays 1.0.0)
# ---------------------------------------------------------------------------

READINESS_SNAPSHOT_SCHEMA_ID: Final = "item9.validation-readiness-snapshot/1.0.0"
METHODOLOGY_FREEZE_SCHEMA_ID: Final = "item9.calibration-methodology-freeze/1.0.0"
PAPER_ACCEPTANCE_SCHEMA_ID: Final = "item9.paper-validation-acceptance/1.0.0"
PROSPECTIVE_PAPER_RUN_PACKAGE_SCHEMA_ID: Final = "item9.prospective-paper-run-package/1.0.0"
CALIBRATION_ARTIFACT_SCHEMA_ID: Final = "item9.calibration-artifact/1.0.0"
AUTHORIZATION_ARTIFACT_SCHEMA_ID: Final = "item9.calibration-authorization/1.0.0"

BOUND_PROTOCOL_VERSION: Final = PROTOCOL_VERSION  # item9.calibration-protocol/1.0.0

# ---------------------------------------------------------------------------
# Row dispositions (forensic / snapshot)
# ---------------------------------------------------------------------------

DISPOSITION_ADMISSIBLE: Final = "ADMISSIBLE"
DISPOSITION_EXCLUDED_WITH_REASON: Final = "EXCLUDED_WITH_REASON"
DISPOSITION_PATH_PROOF_ONLY: Final = "PATH_PROOF_ONLY"
DISPOSITION_EVALUATION_ONLY: Final = "EVALUATION_ONLY"
DISPOSITION_UNKNOWN_REQUIRES_REVIEW: Final = "UNKNOWN_REQUIRES_REVIEW"

# EVALUATION_ONLY is a lifecycle role on an admissible row, not a second
# exclusion and not a double-count against ADMISSIBLE.
EVALUATION_ONLY_IS_LIFECYCLE_ROLE: Final = True

ROW_DISPOSITIONS: Final = frozenset(
    {
        DISPOSITION_ADMISSIBLE,
        DISPOSITION_EXCLUDED_WITH_REASON,
        DISPOSITION_PATH_PROOF_ONLY,
        DISPOSITION_EVALUATION_ONLY,
        DISPOSITION_UNKNOWN_REQUIRES_REVIEW,
    }
)

# ---------------------------------------------------------------------------
# Preflight verdicts
# ---------------------------------------------------------------------------

CALIBRATION_PREFLIGHT_READY: Final = "CALIBRATION_PREFLIGHT_READY"
CALIBRATION_PREFLIGHT_BLOCKED: Final = "CALIBRATION_PREFLIGHT_BLOCKED"

PREFLIGHT_VERDICTS: Final = frozenset(
    {CALIBRATION_PREFLIGHT_READY, CALIBRATION_PREFLIGHT_BLOCKED}
)

# ---------------------------------------------------------------------------
# Readiness state (separate from item9_status=PARTIAL_NOT_CALIBRATED)
# ---------------------------------------------------------------------------

READINESS_STATE_UNSET: Final = "UNSET"
READINESS_STATE_AWAITING_AUTHORIZATION: Final = (
    "ITEM9_CALIBRATION_READY_AWAITING_AUTHORIZATION"
)
READINESS_STATE_NOT_READY: Final = "ITEM9_CALIBRATION_NOT_READY"

READINESS_STATES: Final = frozenset(
    {
        READINESS_STATE_UNSET,
        READINESS_STATE_AWAITING_AUTHORIZATION,
        READINESS_STATE_NOT_READY,
    }
)

# ---------------------------------------------------------------------------
# Authorization (ABSENT does not block preflight READY; blocks execution)
# ---------------------------------------------------------------------------

AUTHORIZATION_ABSENT: Final = "ABSENT"
AUTHORIZATION_PRESENT: Final = "PRESENT"
AUTHORIZATION_INVALID: Final = "INVALID"

AUTHORIZATION_STATES: Final = frozenset(
    {AUTHORIZATION_ABSENT, AUTHORIZATION_PRESENT, AUTHORIZATION_INVALID}
)

ITEM9_CALIBRATION_RUN_FORBIDDEN: Final = "FORBIDDEN"
FITTING_ALLOWED_DEFAULT: Final = False
CALIBRATED_DEFAULT: Final = False

# Execution refusal (before corpus read for result write)
CALIBRATION_EXECUTION_REFUSED: Final = "CALIBRATION_EXECUTION_REFUSED"

# ---------------------------------------------------------------------------
# Field applicability on historical Mode B bar receipts
# ---------------------------------------------------------------------------

FIELD_NOT_APPLICABLE: Final = "NOT_APPLICABLE"
FIELD_NOT_OBSERVED: Final = "NOT_OBSERVED"
FIELD_UNAVAILABLE: Final = "UNAVAILABLE"
FIELD_UNSET_BLOCKING: Final = "UNSET/BLOCKING"
FIELD_NOT_RUN: Final = "NOT_RUN"

# Strategy IDs / operator decisions / order-ready lineage belong to the
# prospective Paper package — NOT_APPLICABLE on Mode B bar receipts.
MODE_B_NOT_APPLICABLE_FIELDS: Final = frozenset(
    {
        "strategy_id",
        "operator_decision_id",
        "order_ready_id",
        "opportunity_id",
        "thesis_id",
        "paper_order_id",
    }
)

# ---------------------------------------------------------------------------
# Governing-rule ids (point at protocol sections / dual-corpus / gap register)
# ---------------------------------------------------------------------------

RULE_PROTOCOL_V1_FREEZE: Final = "RULE.PROTOCOL.V1_FREEZE_RECORD"
RULE_PROTOCOL_SAMPLE_FLOORS: Final = "RULE.PROTOCOL.SAMPLE_FLOORS_20_3_5"
RULE_PROTOCOL_CHRONO_SPLIT: Final = "RULE.PROTOCOL.CHRONOLOGICAL_60_20_20"
RULE_PROTOCOL_SEARCH_COMPLEXITY_0: Final = "RULE.PROTOCOL.SEARCH_COMPLEXITY_0"
RULE_PROTOCOL_NUMERIC_GATES_UNSET: Final = "RULE.PROTOCOL.NUMERIC_GATES_UNSET_BLOCKING"
RULE_PROTOCOL_COSTS_NOT_OBSERVABLE: Final = "RULE.PROTOCOL.COSTS_NOT_OBSERVABLE"
RULE_ADMISSION_PROSPECTIVE: Final = "RULE.ADMISSION.PROSPECTIVE_CORPUS"
RULE_DUAL_CORPUS_LEAK: Final = "RULE.DUAL_CORPUS.CONTAMINATION_AUDITOR"
RULE_DUAL_CORPUS_HOLDOUT: Final = "RULE.DUAL_CORPUS.HOLDOUT_NOT_IN_TRAINING"
RULE_GAP_REGISTER_NOT_OBSERVED: Final = "RULE.GAP_REGISTER.NOT_OBSERVED_INTERVALS"
RULE_FORENSIC_DUPLICATE_HASH: Final = "RULE.FORENSIC.DUPLICATE_FILE_HASH"
RULE_FORENSIC_DUPLICATE_EXPERIMENT: Final = "RULE.FORENSIC.DUPLICATE_EXPERIMENT_ID"
RULE_FORENSIC_TIMESTAMP_ORDER: Final = "RULE.FORENSIC.TIMESTAMP_ORDER"
RULE_FORENSIC_PIT: Final = "RULE.FORENSIC.POINT_IN_TIME"
RULE_FORENSIC_EMPTY_RAW_HASH: Final = "RULE.FORENSIC.EMPTY_RAW_HASH_PATH_PROOF"
RULE_FORENSIC_NON_RTH: Final = "RULE.FORENSIC.NON_RTH"
RULE_FORENSIC_ZERO_PRICE_VOLUME: Final = "RULE.FORENSIC.ZERO_PRICE_OR_VOLUME"
RULE_FORENSIC_INSTRUMENT: Final = "RULE.FORENSIC.INSTRUMENT_IDENTITY"
RULE_FORENSIC_VERSION_DRIFT: Final = "RULE.FORENSIC.SCHEMA_OR_SIMULATOR_VERSION_DRIFT"
RULE_FORENSIC_AUTHORITY_MIXING: Final = "RULE.FORENSIC.HISTORICAL_DEVELOPMENT_MIXING"
RULE_MODE_B_STRATEGY_N_A: Final = "RULE.MODE_B.STRATEGY_FIELDS_NOT_APPLICABLE"
RULE_EVALUATION_LIFECYCLE_ROLE: Final = "RULE.SPLIT.EVALUATION_ONLY_LIFECYCLE_ROLE"
RULE_AUTH_ABSENT_OK_PREFLIGHT: Final = "RULE.AUTH.ABSENT_DOES_NOT_BLOCK_PREFLIGHT"
RULE_AUTH_REQUIRED_FOR_EXECUTE: Final = "RULE.AUTH.REQUIRED_BEFORE_CORPUS_READ_FOR_WRITE"
RULE_NO_PATH_PROOF_IN_CONSUMPTION: Final = "RULE.CONSUMPTION.NO_PATH_PROOF_ONLY"
RULE_UNTOUCHED_EVAL_SEAL: Final = "RULE.SPLIT.UNTOUCHED_EVALUATION_SEAL"
RULE_TOCTOU_FINGERPRINT: Final = "RULE.TOCTOU.PREFLIGHT_FINGERPRINT_BIND"

GOVERNING_RULE_IDS: Final = frozenset(
    {
        RULE_PROTOCOL_V1_FREEZE,
        RULE_PROTOCOL_SAMPLE_FLOORS,
        RULE_PROTOCOL_CHRONO_SPLIT,
        RULE_PROTOCOL_SEARCH_COMPLEXITY_0,
        RULE_PROTOCOL_NUMERIC_GATES_UNSET,
        RULE_PROTOCOL_COSTS_NOT_OBSERVABLE,
        RULE_ADMISSION_PROSPECTIVE,
        RULE_DUAL_CORPUS_LEAK,
        RULE_DUAL_CORPUS_HOLDOUT,
        RULE_GAP_REGISTER_NOT_OBSERVED,
        RULE_FORENSIC_DUPLICATE_HASH,
        RULE_FORENSIC_DUPLICATE_EXPERIMENT,
        RULE_FORENSIC_TIMESTAMP_ORDER,
        RULE_FORENSIC_PIT,
        RULE_FORENSIC_EMPTY_RAW_HASH,
        RULE_FORENSIC_NON_RTH,
        RULE_FORENSIC_ZERO_PRICE_VOLUME,
        RULE_FORENSIC_INSTRUMENT,
        RULE_FORENSIC_VERSION_DRIFT,
        RULE_FORENSIC_AUTHORITY_MIXING,
        RULE_MODE_B_STRATEGY_N_A,
        RULE_EVALUATION_LIFECYCLE_ROLE,
        RULE_AUTH_ABSENT_OK_PREFLIGHT,
        RULE_AUTH_REQUIRED_FOR_EXECUTE,
        RULE_NO_PATH_PROOF_IN_CONSUMPTION,
        RULE_UNTOUCHED_EVAL_SEAL,
        RULE_TOCTOU_FINGERPRINT,
    }
)

# ---------------------------------------------------------------------------
# Preflight reason codes
# ---------------------------------------------------------------------------

REASON_SAMPLE_FLOOR_MET: Final = "SAMPLE_FLOOR_MET"
REASON_SAMPLE_FLOOR_UNMET: Final = "SAMPLE_FLOOR_UNMET"
REASON_RTH_DATES_MET: Final = "RTH_DATES_MET"
REASON_RTH_DATES_UNMET: Final = "RTH_DATES_UNMET"
REASON_EVAL_FLOOR_MET: Final = "EVAL_FLOOR_MET"
REASON_EVAL_FLOOR_UNMET: Final = "EVAL_FLOOR_UNMET"
REASON_CORPUS_FINGERPRINT_OK: Final = "CORPUS_FINGERPRINT_PRESENT"
REASON_PROTOCOL_FINGERPRINT_OK: Final = "PROTOCOL_FINGERPRINT_PRESENT"
REASON_SCHEMA_VERSION_OK: Final = "SCHEMA_VERSION_BOUND"
REASON_SIMULATOR_VERSION_OK: Final = "SIMULATOR_VERSION_BOUND"
REASON_PROVENANCE_OK: Final = "PROVENANCE_COMPLETE"
REASON_PIT_OK: Final = "PIT_CHECKS_PASS"
REASON_EXCLUSION_ACCOUNTED: Final = "EXCLUSION_ACCOUNTING_COMPLETE"
REASON_UNTOUCHED_EVAL_SEALED: Final = "UNTOUCHED_EVAL_SEALED"
REASON_TRAIN_EVAL_SEPARATED: Final = "TRAIN_EVAL_SEPARATED"
REASON_DUPLICATES_REJECTED: Final = "DUPLICATES_REJECTED"
REASON_PATH_PROOF_IN_CONSUMPTION: Final = "PATH_PROOF_ONLY_IN_CONSUMPTION_SET"
REASON_CRITICAL_UNKNOWN: Final = "CRITICAL_UNKNOWN_REQUIRES_REVIEW"
REASON_DETERMINISTIC_ORDERING: Final = "DETERMINISTIC_ORDERING_OK"
REASON_RECEIPT_DIR_UNAVAILABLE: Final = "RECEIPT_DIR_UNAVAILABLE"
REASON_GAP_REGISTER_LOADED: Final = "GAP_REGISTER_LOADED"
REASON_AUTHORIZATION_ABSENT_REPORTED: Final = "AUTHORIZATION_ABSENT_REPORTED"
REASON_INTEGRITY_FAILURE: Final = "INTEGRITY_FAILURE"
REASON_HOLDOUT_LEAK: Final = "HOLDOUT_IN_DEVELOPMENT_OR_SELECTION"
REASON_AUTHORITY_MIXING: Final = "HISTORICAL_DEVELOPMENT_AUTHORITY_MIXING"
REASON_CONTAMINATION_AUDIT_FAIL: Final = "CONTAMINATION_AUDIT_FAIL"
REASON_PROTECTED_EVAL_CONSUMED: Final = "PROTECTED_EVAL_CONSUMED_FOR_TRAINING"
REASON_TOCTOU_FINGERPRINT_MISMATCH: Final = "TOCTOU_FINGERPRINT_MISMATCH"
REASON_TOCTOU_FINGERPRINT_BOUND: Final = "TOCTOU_FINGERPRINT_BOUND"

# ---------------------------------------------------------------------------
# Paper acceptance lifecycle (independent; never auto-promote)
# ---------------------------------------------------------------------------

PAPER_STATE_CALIBRATED: Final = "CALIBRATED"
PAPER_STATE_VALIDATION_READY: Final = "PAPER_VALIDATION_READY"
PAPER_STATE_EMPIRICAL_ACTIVE: Final = "PAPER_EMPIRICAL_ACTIVE"
PAPER_STATE_VALIDATION_COMPLETE: Final = "PAPER_VALIDATION_COMPLETE"
PAPER_STATE_VALIDATED: Final = "PAPER_VALIDATED"

PAPER_LIFECYCLE_STATES: Final = (
    PAPER_STATE_CALIBRATED,
    PAPER_STATE_VALIDATION_READY,
    PAPER_STATE_EMPIRICAL_ACTIVE,
    PAPER_STATE_VALIDATION_COMPLETE,
    PAPER_STATE_VALIDATED,
)

# Protocol freeze provenance (recorded; not retuned from corpus)
PROTOCOL_FREEZE_PR: Final = "#234"
PROTOCOL_FREEZE_COMMIT_HINT: Final = "f47b449a"
SEARCH_COMPLEXITY_MAX: Final = 0


def contract_freeze_record() -> dict[str, object]:
    """Machine-readable companion freeze bound to protocol 1.0.0."""

    return {
        "bound_protocol_version": BOUND_PROTOCOL_VERSION,
        "readiness_snapshot_schema_id": READINESS_SNAPSHOT_SCHEMA_ID,
        "methodology_freeze_schema_id": METHODOLOGY_FREEZE_SCHEMA_ID,
        "paper_acceptance_schema_id": PAPER_ACCEPTANCE_SCHEMA_ID,
        "fitting_allowed": FITTING_ALLOWED_DEFAULT,
        "calibrated": CALIBRATED_DEFAULT,
        "item9_calibration_run": ITEM9_CALIBRATION_RUN_FORBIDDEN,
        "search_complexity_max": SEARCH_COMPLEXITY_MAX,
        "protocol_freeze_pr": PROTOCOL_FREEZE_PR,
        "protocol_freeze_commit_hint": PROTOCOL_FREEZE_COMMIT_HINT,
        "evaluation_only_is_lifecycle_role": EVALUATION_ONLY_IS_LIFECYCLE_ROLE,
        "authorization_absent_blocks_preflight": False,
        "authorization_absent_blocks_execution": True,
        "mode_b_not_applicable_fields": sorted(MODE_B_NOT_APPLICABLE_FIELDS),
        "row_dispositions": sorted(ROW_DISPOSITIONS),
        "preflight_verdicts": sorted(PREFLIGHT_VERDICTS),
        "readiness_states": sorted(READINESS_STATES),
        "authorization_states": sorted(AUTHORIZATION_STATES),
        "governing_rule_ids": sorted(GOVERNING_RULE_IDS),
        "paper_lifecycle_states": list(PAPER_LIFECYCLE_STATES),
        "live_execution": "OFF",
    }


__all__ = [
    "AUTHORIZATION_ABSENT",
    "AUTHORIZATION_ARTIFACT_SCHEMA_ID",
    "AUTHORIZATION_INVALID",
    "AUTHORIZATION_PRESENT",
    "AUTHORIZATION_STATES",
    "BOUND_PROTOCOL_VERSION",
    "CALIBRATED_DEFAULT",
    "CALIBRATION_ARTIFACT_SCHEMA_ID",
    "CALIBRATION_EXECUTION_REFUSED",
    "CALIBRATION_PREFLIGHT_BLOCKED",
    "CALIBRATION_PREFLIGHT_READY",
    "DISPOSITION_ADMISSIBLE",
    "DISPOSITION_EVALUATION_ONLY",
    "DISPOSITION_EXCLUDED_WITH_REASON",
    "DISPOSITION_PATH_PROOF_ONLY",
    "DISPOSITION_UNKNOWN_REQUIRES_REVIEW",
    "EVALUATION_ONLY_IS_LIFECYCLE_ROLE",
    "FIELD_NOT_APPLICABLE",
    "FIELD_NOT_OBSERVED",
    "FIELD_NOT_RUN",
    "FIELD_UNAVAILABLE",
    "FIELD_UNSET_BLOCKING",
    "FITTING_ALLOWED_DEFAULT",
    "GOVERNING_RULE_IDS",
    "ITEM9_CALIBRATION_RUN_FORBIDDEN",
    "METHODOLOGY_FREEZE_SCHEMA_ID",
    "MODE_B_NOT_APPLICABLE_FIELDS",
    "PAPER_ACCEPTANCE_SCHEMA_ID",
    "PAPER_LIFECYCLE_STATES",
    "PAPER_STATE_CALIBRATED",
    "PAPER_STATE_EMPIRICAL_ACTIVE",
    "PAPER_STATE_VALIDATED",
    "PAPER_STATE_VALIDATION_COMPLETE",
    "PAPER_STATE_VALIDATION_READY",
    "PREFLIGHT_VERDICTS",
    "PROTOCOL_FREEZE_COMMIT_HINT",
    "PROTOCOL_FREEZE_PR",
    "PROSPECTIVE_PAPER_RUN_PACKAGE_SCHEMA_ID",
    "READINESS_SNAPSHOT_SCHEMA_ID",
    "READINESS_STATES",
    "READINESS_STATE_AWAITING_AUTHORIZATION",
    "READINESS_STATE_NOT_READY",
    "READINESS_STATE_UNSET",
    "REASON_AUTHORIZATION_ABSENT_REPORTED",
    "REASON_AUTHORITY_MIXING",
    "REASON_CONTAMINATION_AUDIT_FAIL",
    "REASON_CORPUS_FINGERPRINT_OK",
    "REASON_CRITICAL_UNKNOWN",
    "REASON_DETERMINISTIC_ORDERING",
    "REASON_DUPLICATES_REJECTED",
    "REASON_EVAL_FLOOR_MET",
    "REASON_EVAL_FLOOR_UNMET",
    "REASON_EXCLUSION_ACCOUNTED",
    "REASON_GAP_REGISTER_LOADED",
    "REASON_HOLDOUT_LEAK",
    "REASON_INTEGRITY_FAILURE",
    "REASON_PATH_PROOF_IN_CONSUMPTION",
    "REASON_PIT_OK",
    "REASON_PROTECTED_EVAL_CONSUMED",
    "REASON_PROTOCOL_FINGERPRINT_OK",
    "REASON_PROVENANCE_OK",
    "REASON_RECEIPT_DIR_UNAVAILABLE",
    "REASON_RTH_DATES_MET",
    "REASON_RTH_DATES_UNMET",
    "REASON_SAMPLE_FLOOR_MET",
    "REASON_SAMPLE_FLOOR_UNMET",
    "REASON_SCHEMA_VERSION_OK",
    "REASON_SIMULATOR_VERSION_OK",
    "REASON_TOCTOU_FINGERPRINT_BOUND",
    "REASON_TOCTOU_FINGERPRINT_MISMATCH",
    "REASON_TRAIN_EVAL_SEPARATED",
    "REASON_UNTOUCHED_EVAL_SEALED",
    "ROW_DISPOSITIONS",
    "RULE_ADMISSION_PROSPECTIVE",
    "RULE_AUTH_ABSENT_OK_PREFLIGHT",
    "RULE_AUTH_REQUIRED_FOR_EXECUTE",
    "RULE_DUAL_CORPUS_HOLDOUT",
    "RULE_DUAL_CORPUS_LEAK",
    "RULE_EVALUATION_LIFECYCLE_ROLE",
    "RULE_FORENSIC_AUTHORITY_MIXING",
    "RULE_FORENSIC_DUPLICATE_EXPERIMENT",
    "RULE_FORENSIC_DUPLICATE_HASH",
    "RULE_FORENSIC_EMPTY_RAW_HASH",
    "RULE_FORENSIC_INSTRUMENT",
    "RULE_FORENSIC_NON_RTH",
    "RULE_FORENSIC_PIT",
    "RULE_FORENSIC_TIMESTAMP_ORDER",
    "RULE_FORENSIC_VERSION_DRIFT",
    "RULE_FORENSIC_ZERO_PRICE_VOLUME",
    "RULE_GAP_REGISTER_NOT_OBSERVED",
    "RULE_MODE_B_STRATEGY_N_A",
    "RULE_NO_PATH_PROOF_IN_CONSUMPTION",
    "RULE_PROTOCOL_CHRONO_SPLIT",
    "RULE_PROTOCOL_COSTS_NOT_OBSERVABLE",
    "RULE_PROTOCOL_NUMERIC_GATES_UNSET",
    "RULE_PROTOCOL_SAMPLE_FLOORS",
    "RULE_PROTOCOL_SEARCH_COMPLEXITY_0",
    "RULE_PROTOCOL_V1_FREEZE",
    "RULE_UNTOUCHED_EVAL_SEAL",
    "RULE_TOCTOU_FINGERPRINT",
    "SEARCH_COMPLEXITY_MAX",
    "contract_freeze_record",
]
