"""Stable OF-02 adapter error codes."""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Mapping


class OF02ErrorCode(StrEnum):
    ADAPTER_DISABLED = "OF02_ADAPTER_DISABLED"
    WRITER_UNAVAILABLE = "OF02_WRITER_UNAVAILABLE"
    ATTRIBUTION_FAILED = "OF02_ATTRIBUTION_FAILED"
    ATTRIBUTION_CONFLICT = "OF02_ATTRIBUTION_CONFLICT"
    ACCEPTANCE_WITHHELD = "OF02_ACCEPTANCE_WITHHELD"
    AUTHORITY_FAIL_CLOSED = "OF02_AUTHORITY_FAIL_CLOSED"
    SOURCE_MISSING = "OF02_SOURCE_MISSING"
    SOURCE_CHANGED = "OF02_SOURCE_CHANGED"
    SOURCE_CONFLICT = "OF02_SOURCE_CONFLICT"
    FABRICATION_PROHIBITED = "OF02_FABRICATION_PROHIBITED"
    BACKDATE_PROHIBITED = "OF02_BACKDATE_PROHIBITED"
    DIRECT_SQL_PROHIBITED = "OF02_DIRECT_SQL_PROHIBITED"
    RETRY_IDENTITY_REGENERATION = "OF02_RETRY_IDENTITY_REGENERATION"
    FUTURE_INFORMATION = "OF02_FUTURE_INFORMATION"
    LIVE_SMOKE_FABRICATED = "OF02_LIVE_SMOKE_FABRICATED"


class OF02Error(Exception):
    def __init__(self, code: OF02ErrorCode, message: str, details: Mapping[str, Any] | None = None) -> None:
        self.code = code
        self.message = message
        self.details = dict(details or {})
        super().__init__(f"{code}: {message}")
