"""Forward shadow qualification package (BUILD 26)."""

from .evidence01 import (
    assess_forward_evidence_qualification,
    build_forward_evidence_qualification_policy,
    build_forward_evidence_qualification_report,
    ForwardEvidenceDisposition,
    ForwardEvidenceQualificationAssessmentV1,
    ForwardEvidenceQualificationPolicyV1,
    ForwardEvidenceQualificationReportV1,
    ForwardObservationInputV1,
    SettlementRateState,
    forward_evidence_assessment_v1_to_dict,
    forward_evidence_policy_v1_to_dict,
    forward_evidence_report_v1_to_dict,
)
from .evidence01a import CampaignEvidenceOrigin, CampaignService
from .evidence01b import CampaignRuntimeService
from .fixture_lifecycle import FixtureLifecycleResult, run_prospective_fixture_lifecycle
from .identity import (
    derive_forward_cohort_fingerprint,
    derive_qualification_report_id,
    derive_qualification_run_id,
    derive_qualification_spec_id,
    derive_receipt_content_hash,
    derive_receipt_id,
)
from .integrity import detect_run_freeze_violation
from .provider_capabilities import (
    probe_all_provider_capabilities,
    probe_ibkr_capabilities,
    probe_moomoo_capabilities,
    provider_capability_matrix,
)
from .rc_integrity import RCIntegrityResult, verify_build25_rc_integrity
from .receipt import build_forward_prediction_receipt, validate_forward_integrity
from .report import build_forward_qualification_report
from .run import build_forward_qualification_run
from .runner import ForwardQualificationRunResult, run_forward_qualification
from .scenarios import REQUIRED_SCENARIOS, SCENARIO_REGISTRY, ScenarioResultV1, ScenarioStatus, run_scenarios
from .serialization import (
    forward_prediction_receipt_v1_to_dict,
    forward_qualification_report_v1_to_dict,
    forward_qualification_run_v1_to_dict,
    forward_qualification_spec_v1_to_dict,
    provider_capability_entry_v1_to_dict,
)
from .spec import BUILD25_RC_BRANCH, build_forward_qualification_spec
from .types import (
    DEFAULT_HORIZON_NS,
    DEFAULT_INSTRUMENT_UNIVERSE,
    DEFAULT_MINIMUM_DURATION_NS,
    DEFAULT_MINIMUM_LABELABLE_COUNT,
    DEFAULT_MINIMUM_PREDICTION_COUNT,
    DEFAULT_TARGET_KIND,
    FORWARD_QUALIFICATION_IMPLEMENTATION_VERSION,
    FORWARD_QUALIFICATION_SCHEMA_VERSION,
    EvidenceClass,
    ForwardIntegrityStatus,
    ForwardPredictionReceiptV1,
    ForwardQualificationReportV1,
    ForwardQualificationRunV1,
    ForwardQualificationSpecV1,
    IntegrityFailureCode,
    ProviderCapabilityEntryV1,
    ProviderRuntimeStatus,
    QualificationDisposition,
    QualificationKind,
)

__all__ = [
    "CampaignEvidenceOrigin",
    "CampaignRuntimeService",
    "CampaignService",
    "ForwardEvidenceDisposition",
    "ForwardEvidenceQualificationAssessmentV1",
    "ForwardEvidenceQualificationPolicyV1",
    "ForwardEvidenceQualificationReportV1",
    "ForwardObservationInputV1",
    "assess_forward_evidence_qualification",
    "build_forward_evidence_qualification_policy",
    "build_forward_evidence_qualification_report",
    "forward_evidence_assessment_v1_to_dict",
    "forward_evidence_policy_v1_to_dict",
    "forward_evidence_report_v1_to_dict",
    "BUILD25_RC_BRANCH",
    "DEFAULT_HORIZON_NS",
    "DEFAULT_INSTRUMENT_UNIVERSE",
    "DEFAULT_MINIMUM_DURATION_NS",
    "DEFAULT_MINIMUM_LABELABLE_COUNT",
    "DEFAULT_MINIMUM_PREDICTION_COUNT",
    "DEFAULT_TARGET_KIND",
    "FORWARD_QUALIFICATION_IMPLEMENTATION_VERSION",
    "FORWARD_QUALIFICATION_SCHEMA_VERSION",
    "EvidenceClass",
    "FixtureLifecycleResult",
    "ForwardIntegrityStatus",
    "ForwardPredictionReceiptV1",
    "ForwardQualificationReportV1",
    "ForwardQualificationRunResult",
    "ForwardQualificationRunV1",
    "ForwardQualificationSpecV1",
    "IntegrityFailureCode",
    "ProviderCapabilityEntryV1",
    "ProviderRuntimeStatus",
    "QualificationDisposition",
    "QualificationKind",
    "RCIntegrityResult",
    "REQUIRED_SCENARIOS",
    "SCENARIO_REGISTRY",
    "ScenarioResultV1",
    "ScenarioStatus",
    "SettlementRateState",
    "build_forward_prediction_receipt",
    "build_forward_qualification_report",
    "build_forward_qualification_run",
    "build_forward_qualification_spec",
    "derive_forward_cohort_fingerprint",
    "derive_qualification_report_id",
    "derive_qualification_run_id",
    "derive_qualification_spec_id",
    "derive_receipt_content_hash",
    "derive_receipt_id",
    "detect_run_freeze_violation",
    "forward_prediction_receipt_v1_to_dict",
    "forward_qualification_report_v1_to_dict",
    "forward_qualification_run_v1_to_dict",
    "forward_qualification_spec_v1_to_dict",
    "probe_all_provider_capabilities",
    "probe_ibkr_capabilities",
    "probe_moomoo_capabilities",
    "provider_capability_entry_v1_to_dict",
    "provider_capability_matrix",
    "run_forward_qualification",
    "run_prospective_fixture_lifecycle",
    "run_scenarios",
    "validate_forward_integrity",
    "verify_build25_rc_integrity",
]
