"""Closed vocabularies for OF-03 registries."""

from __future__ import annotations

from enum import StrEnum


class EffectClass(StrEnum):
    READ_ONLY = "READ_ONLY"
    OBSERVATIONAL = "OBSERVATIONAL"
    NON_DESTRUCTIVE_MUTATION = "NON_DESTRUCTIVE_MUTATION"
    AUTHORITATIVE_MUTATION = "AUTHORITATIVE_MUTATION"
    DESTRUCTIVE_MAINTENANCE = "DESTRUCTIVE_MAINTENANCE"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"


class AutomationPolicy(StrEnum):
    AUTOMATION_ALLOWED = "AUTOMATION_ALLOWED"
    AUTOMATION_ALLOWED_WITH_GUARD = "AUTOMATION_ALLOWED_WITH_GUARD"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    AGENT_PROHIBITED = "AGENT_PROHIBITED"


class HumanApprovalPolicy(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"


class BindingKind(StrEnum):
    PYTHON_API = "PYTHON_API"
    CLI_CAPABILITY = "CLI_CAPABILITY"
    DOCUMENTED_MANUAL_OPERATION = "DOCUMENTED_MANUAL_OPERATION"
    UNBOUND = "UNBOUND"


class RegistrationState(StrEnum):
    DECLARED = "DECLARED"
    DEPRECATED = "DEPRECATED"


class AvailabilityState(StrEnum):
    UNBOUND = "UNBOUND"
    BOUND = "BOUND"
    AVAILABLE = "AVAILABLE"
    DISABLED = "DISABLED"
    UNAVAILABLE = "UNAVAILABLE"
    DEPRECATED = "DEPRECATED"


class SopMaturity(StrEnum):
    DRAFT = "DRAFT"
    NORMATIVE = "NORMATIVE"
    BOUND = "BOUND"


class FindingSeverity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


class StepKind(StrEnum):
    CAPABILITY = "CAPABILITY"
    SOP = "SOP"
    GATE = "GATE"
    PROCEDURE = "PROCEDURE"
    TERMINAL = "TERMINAL"


class GateKind(StrEnum):
    AUTHORITY = "AUTHORITY"
    HUMAN_APPROVAL = "HUMAN_APPROVAL"
    EVIDENCE_PREREQUISITE = "EVIDENCE_PREREQUISITE"
    CAPABILITY_AVAILABILITY = "CAPABILITY_AVAILABILITY"
    INPUT_SCHEMA = "INPUT_SCHEMA"


class IdempotencyClass(StrEnum):
    SAFE_REPEATABLE = "SAFE_REPEATABLE"
    CONDITIONAL = "CONDITIONAL"
    NOT_IDEMPOTENT = "NOT_IDEMPOTENT"
    UNKNOWN = "UNKNOWN"


class RetryClass(StrEnum):
    NONE = "NONE"
    SAME_IDENTITY = "SAME_IDENTITY"
    FRESH_ATTEMPT = "FRESH_ATTEMPT"
    UNKNOWN = "UNKNOWN"


class AttributionRequirement(StrEnum):
    NONE = "NONE"
    OPTIONAL = "OPTIONAL"
    REQUIRED = "REQUIRED"
    NATIVE = "NATIVE"


class FeatureGateKind(StrEnum):
    ENV_TRUTHY = "ENV_TRUTHY"


class AgentUseDecision(StrEnum):
    DESCRIBE_ONLY = "DESCRIBE_ONLY"
    DENIED_AGENT_PROHIBITED = "DENIED_AGENT_PROHIBITED"
    DENIED_HUMAN_APPROVAL_REQUIRED = "DENIED_HUMAN_APPROVAL_REQUIRED"
    DENIED_DESTRUCTIVE = "DENIED_DESTRUCTIVE"
    DENIED_REGISTRY_DOES_NOT_AUTHORIZE = "DENIED_REGISTRY_DOES_NOT_AUTHORIZE"
    GUARDED_METADATA_ONLY = "GUARDED_METADATA_ONLY"
