"""CONTROLLED REPLAY operator golden path — opt-in, non-Live, real stack.

Evidence class: CONTROLLED_REPLAY / SOFTWARE. Never Live. Never broker submit.
Reuses FIXTURE_REPLAY data_mode and the production ingest → OE → Radar path.
"""

from __future__ import annotations

CONTROLLED_REPLAY_FLAG = "IMP_CONTROLLED_REPLAY"
CONTROLLED_REPLAY_EVIDENCE_CLASS = "CONTROLLED_REPLAY"
CONTROLLED_REPLAY_OPPORTUNITY_SOURCE = "CONTROLLED_REPLAY"
CONTROLLED_REPLAY_STATE_DIRNAME = "controlled-replay"
CONTROLLED_REPLAY_OPERATOR_URL_PATH = "/radar"

__all__ = [
    "CONTROLLED_REPLAY_EVIDENCE_CLASS",
    "CONTROLLED_REPLAY_FLAG",
    "CONTROLLED_REPLAY_OPPORTUNITY_SOURCE",
    "CONTROLLED_REPLAY_OPERATOR_URL_PATH",
    "CONTROLLED_REPLAY_STATE_DIRNAME",
]
