"""Order Flow quality taxonomy — reuse shared flags where equivalent."""

from __future__ import annotations

from enum import StrEnum


class OrderFlowQualityFlag(StrEnum):
    AGGRESSOR_UNKNOWN = "AGGRESSOR_UNKNOWN"
    AGGRESSOR_LOW_CONFIDENCE = "AGGRESSOR_LOW_CONFIDENCE"
    TRADE_FEED_STALE = "TRADE_FEED_STALE"
    BOOK_STALE = "BOOK_STALE"
    DEPTH_PARTIAL = "DEPTH_PARTIAL"
    SEQUENCE_GAP = "SEQUENCE_GAP"
    BOOK_DESYNC = "BOOK_DESYNC"
    VENUE_PARTIAL = "VENUE_PARTIAL"
    MBO_UNAVAILABLE = "MBO_UNAVAILABLE"
    QUOTE_TRADE_CLOCK_MISMATCH = "QUOTE_TRADE_CLOCK_MISMATCH"
    SPREAD_ABNORMAL = "SPREAD_ABNORMAL"
    CROSSED_BOOK = "CROSSED_BOOK"
    LOCKED_BOOK = "LOCKED_BOOK"
    MICROSTRUCTURE_CAPABILITY_UNAVAILABLE = "MICROSTRUCTURE_CAPABILITY_UNAVAILABLE"


__all__ = ["OrderFlowQualityFlag"]
