"""Operational reliability package (BUILD 32)."""

from .alerts import (
    acknowledge_alert,
    alerts_from_slo_assessment,
    build_default_alert_policy,
    build_dedup_key,
    raise_alert,
    should_dedup_alert,
)
from .backup import collect_backup_scope, create_backup_manifest, restore_kill_switch_from_backup, verify_backup_integrity
from .delivery import (
    ConsoleAlertDeliveryAdapter,
    NotConfiguredDeliveryAdapter,
    deliver_alert,
    sanitize_alert_payload,
)
from .drills import DR_DRILL_SPECS, run_all_dr_drills, run_dr_drill
from .health_matrix import build_operational_health_matrix, collect_heartbeats_from_context
from .heartbeats import (
    CRITICAL_COMPONENTS,
    DEFAULT_HEARTBEAT_INTERVAL_NS,
    DEFAULT_STALE_AFTER_NS,
    aggregate_observability_state,
    build_component_heartbeat,
    evaluate_heartbeat_staleness,
)
from .identity import (
    derive_alert_id,
    derive_alert_policy_id,
    derive_backup_manifest_id,
    derive_delivery_receipt_id,
    derive_drill_report_id,
    derive_health_matrix_id,
    derive_persistence_health_id,
    derive_qualification_report_id,
    derive_recovery_plan_id,
    derive_slo_assessment_id,
    derive_slo_policy_id,
    derive_soak_report_id,
)
from .persistence_health import assess_persistence_health
from .qualification import build_operational_reliability_qualification_report
from .readiness import block_gate_for_operational_readiness, evaluate_operational_readiness_blocks_live
from .recovery import RECOVERED_STARTUP_MODE, build_default_recovery_plan, recovered_runtime_blocks_live
from .slo import assess_operational_slos, build_default_slo_policy
from .soak import build_default_soak_spec, run_virtual_soak_endurance
from .telemetry import build_operational_reliability_snapshot
from .types import (
    ALLOWED_METRIC_DIMENSIONS,
    BUILD32_KNOWN_LIMITATIONS,
    OPERATIONAL_RELIABILITY_IMPLEMENTATION_VERSION,
    OPERATIONAL_RELIABILITY_SCHEMA_VERSION,
    AlertDeliveryReceiptV1,
    AlertPolicyV1,
    AlertSeverity,
    AlertState,
    AlertV1,
    BackupManifestV1,
    ComponentHeartbeatV1,
    ComponentHealthClass,
    ComponentSignalState,
    DeliveryResult,
    DisasterRecoveryDrillReportV1,
    DisasterRecoveryDrillSpecV1,
    DrillResult,
    OperationalHealthMatrixEntryV1,
    OperationalHealthMatrixV1,
    OperationalReliabilityDisposition,
    OperationalReliabilityQualificationReportV1,
    OperationalSLOAssessmentV1,
    OperationalSLOPolicyV1,
    PersistenceHealthSnapshotV1,
    RecoveryPlanV1,
    SLOObjectiveResultV1,
    SLOObjectiveStatus,
    SLOObjectiveV1,
    SoakQualificationReportV1,
    SoakQualificationSpecV1,
)

__all__ = [
    "ALLOWED_METRIC_DIMENSIONS",
    "BUILD32_KNOWN_LIMITATIONS",
    "CRITICAL_COMPONENTS",
    "DEFAULT_HEARTBEAT_INTERVAL_NS",
    "DEFAULT_STALE_AFTER_NS",
    "DR_DRILL_SPECS",
    "OPERATIONAL_RELIABILITY_IMPLEMENTATION_VERSION",
    "OPERATIONAL_RELIABILITY_SCHEMA_VERSION",
    "RECOVERED_STARTUP_MODE",
    "AlertDeliveryReceiptV1",
    "AlertPolicyV1",
    "AlertSeverity",
    "AlertState",
    "AlertV1",
    "BackupManifestV1",
    "ComponentHealthClass",
    "ComponentHeartbeatV1",
    "ComponentSignalState",
    "ConsoleAlertDeliveryAdapter",
    "DeliveryResult",
    "DisasterRecoveryDrillReportV1",
    "DisasterRecoveryDrillSpecV1",
    "DrillResult",
    "NotConfiguredDeliveryAdapter",
    "OperationalHealthMatrixEntryV1",
    "OperationalHealthMatrixV1",
    "OperationalReliabilityDisposition",
    "OperationalReliabilityQualificationReportV1",
    "OperationalSLOAssessmentV1",
    "OperationalSLOPolicyV1",
    "PersistenceHealthSnapshotV1",
    "RecoveryPlanV1",
    "SLOObjectiveResultV1",
    "SLOObjectiveStatus",
    "SLOObjectiveV1",
    "SoakQualificationReportV1",
    "SoakQualificationSpecV1",
    "acknowledge_alert",
    "aggregate_observability_state",
    "alerts_from_slo_assessment",
    "assess_operational_slos",
    "assess_persistence_health",
    "block_gate_for_operational_readiness",
    "build_component_heartbeat",
    "build_default_alert_policy",
    "build_default_recovery_plan",
    "build_default_slo_policy",
    "build_default_soak_spec",
    "build_dedup_key",
    "build_operational_health_matrix",
    "build_operational_reliability_qualification_report",
    "build_operational_reliability_snapshot",
    "collect_backup_scope",
    "collect_heartbeats_from_context",
    "create_backup_manifest",
    "deliver_alert",
    "derive_alert_id",
    "derive_alert_policy_id",
    "derive_backup_manifest_id",
    "derive_delivery_receipt_id",
    "derive_drill_report_id",
    "derive_health_matrix_id",
    "derive_persistence_health_id",
    "derive_qualification_report_id",
    "derive_recovery_plan_id",
    "derive_slo_assessment_id",
    "derive_slo_policy_id",
    "derive_soak_report_id",
    "evaluate_heartbeat_staleness",
    "evaluate_operational_readiness_blocks_live",
    "raise_alert",
    "recovered_runtime_blocks_live",
    "restore_kill_switch_from_backup",
    "run_all_dr_drills",
    "run_dr_drill",
    "run_virtual_soak_endurance",
    "sanitize_alert_payload",
    "should_dedup_alert",
    "verify_backup_integrity",
]
