"""Quality flags for FRED / ALFRED macro evidence."""

from __future__ import annotations

from enum import StrEnum


class FredQualityFlag(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    AUTH_FAILED = "AUTH_FAILED"
    SERIES_UNAVAILABLE = "SERIES_UNAVAILABLE"
    RELEASE_NOT_YET_UPDATED = "RELEASE_NOT_YET_UPDATED"
    MIXED_RELEASE_UPDATE = "MIXED_RELEASE_UPDATE"
    V1_V2_RECONCILIATION_MISMATCH = "V1_V2_RECONCILIATION_MISMATCH"
    PIT_UNAVAILABLE = "PIT_UNAVAILABLE"
    PIT_UNCERTAIN = "PIT_UNCERTAIN"
    VINTAGE_UNAVAILABLE = "VINTAGE_UNAVAILABLE"
    MISSING_VALUE = "MISSING_VALUE"
    SERIES_DISCONTINUED = "SERIES_DISCONTINUED"
    METHODOLOGY_CHANGED = "METHODOLOGY_CHANGED"
    COPYRIGHT_RESTRICTED = "COPYRIGHT_RESTRICTED"
    SOURCE_MAPPING_UNRESOLVED = "SOURCE_MAPPING_UNRESOLVED"
    SCHEMA_CHANGED = "SCHEMA_CHANGED"
    CURSOR_LOOP = "CURSOR_LOOP"
    CURSOR_MISSING = "CURSOR_MISSING"
    PARTIAL_RELEASE_RETRIEVAL = "PARTIAL_RELEASE_RETRIEVAL"


_BLOCKING_FLAGS = frozenset(
    {
        FredQualityFlag.SOURCE_UNAVAILABLE,
        FredQualityFlag.AUTH_FAILED,
        FredQualityFlag.PIT_UNAVAILABLE,
        FredQualityFlag.V1_V2_RECONCILIATION_MISMATCH,
        FredQualityFlag.MIXED_RELEASE_UPDATE,
        FredQualityFlag.PARTIAL_RELEASE_RETRIEVAL,
    }
)


def quality_blocks_macro(flags: tuple[str, ...]) -> bool:
    return any(flag in _BLOCKING_FLAGS for flag in flags)


__all__ = ["FredQualityFlag", "quality_blocks_macro"]
