"""Construction helpers for honest trade reviews across execution modes."""

from __future__ import annotations

from typing import Any

from ..contracts.common import ContractReference
from ..opportunity.lifecycle import OperatorLifecycleState
from .contracts import (
    TRADE_REVIEW_SCHEMA_VERSION,
    TradeExecutionAttribution,
    TradeReviewMode,
    TradeReviewV1,
)
from .identity import derive_trade_review_id


def _base_review_fields(
    *,
    review_mode: TradeReviewMode,
    decision: str,
    decision_time_ns: int,
    created_at_ns: int,
    opportunity_id: str | None,
    strategy_id: str | None,
    ftep_campaign: str | None,
    ftep_session_id: str | None,
    evidence_snapshot_refs: tuple[ContractReference, ...],
    contradictions: tuple[str, ...],
    risk_snapshot: dict[str, Any] | None,
    preview_refs: tuple[ContractReference, ...],
    tags: tuple[str, ...],
    mistakes: tuple[str, ...],
    notes: str,
    reflection: str,
    metadata: dict[str, Any] | None,
) -> TradeReviewV1:
    review_id = derive_trade_review_id(
        review_mode=review_mode,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        decision=decision,
        decision_time_ns=decision_time_ns,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
    )
    return TradeReviewV1(
        review_id=review_id,
        schema_version=TRADE_REVIEW_SCHEMA_VERSION,
        review_mode=review_mode,
        decision=decision,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        preview_refs=preview_refs,
        execution_attribution=None,
        execution_decision_trace_id=None,
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=dict(metadata or {}),
    )


def build_rejected_opportunity_review(
    *,
    opportunity_id: str,
    strategy_id: str | None,
    decision_time_ns: int,
    created_at_ns: int,
    evidence_snapshot_refs: tuple[ContractReference, ...] = (),
    contradictions: tuple[str, ...] = (),
    risk_snapshot: dict[str, Any] | None = None,
    ftep_campaign: str | None = None,
    ftep_session_id: str | None = None,
    tags: tuple[str, ...] = (),
    mistakes: tuple[str, ...] = (),
    notes: str = "",
    reflection: str = "",
    metadata: dict[str, Any] | None = None,
) -> TradeReviewV1:
    return _base_review_fields(
        review_mode=TradeReviewMode.REJECTED_OPPORTUNITY,
        decision=OperatorLifecycleState.DISMISSED.value,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        preview_refs=(),
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=metadata,
    )


def build_watched_opportunity_review(
    *,
    opportunity_id: str,
    strategy_id: str | None,
    decision_time_ns: int,
    created_at_ns: int,
    evidence_snapshot_refs: tuple[ContractReference, ...] = (),
    contradictions: tuple[str, ...] = (),
    risk_snapshot: dict[str, Any] | None = None,
    ftep_campaign: str | None = None,
    ftep_session_id: str | None = None,
    tags: tuple[str, ...] = (),
    mistakes: tuple[str, ...] = (),
    notes: str = "",
    reflection: str = "",
    metadata: dict[str, Any] | None = None,
) -> TradeReviewV1:
    return _base_review_fields(
        review_mode=TradeReviewMode.WATCHED_OPPORTUNITY,
        decision=OperatorLifecycleState.WATCHED.value,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        preview_refs=(),
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=metadata,
    )


def _executed_review(
    *,
    review_mode: TradeReviewMode,
    opportunity_id: str | None,
    strategy_id: str | None,
    decision: str,
    decision_time_ns: int,
    created_at_ns: int,
    execution_attribution: TradeExecutionAttribution,
    execution_decision_trace_id: str | None,
    evidence_snapshot_refs: tuple[ContractReference, ...],
    preview_refs: tuple[ContractReference, ...],
    contradictions: tuple[str, ...],
    risk_snapshot: dict[str, Any] | None,
    ftep_campaign: str | None,
    ftep_session_id: str | None,
    tags: tuple[str, ...],
    mistakes: tuple[str, ...],
    notes: str,
    reflection: str,
    metadata: dict[str, Any] | None,
) -> TradeReviewV1:
    review_id = derive_trade_review_id(
        review_mode=review_mode,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        decision=decision,
        decision_time_ns=decision_time_ns,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
    )
    return TradeReviewV1(
        review_id=review_id,
        schema_version=TRADE_REVIEW_SCHEMA_VERSION,
        review_mode=review_mode,
        decision=decision,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        preview_refs=preview_refs,
        execution_attribution=execution_attribution,
        execution_decision_trace_id=execution_decision_trace_id,
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=dict(metadata or {}),
    )


def build_paper_trade_review(
    *,
    opportunity_id: str | None,
    strategy_id: str | None,
    decision: str,
    decision_time_ns: int,
    created_at_ns: int,
    execution_attribution: TradeExecutionAttribution,
    execution_decision_trace_id: str | None = None,
    evidence_snapshot_refs: tuple[ContractReference, ...] = (),
    preview_refs: tuple[ContractReference, ...] = (),
    contradictions: tuple[str, ...] = (),
    risk_snapshot: dict[str, Any] | None = None,
    ftep_campaign: str | None = None,
    ftep_session_id: str | None = None,
    tags: tuple[str, ...] = (),
    mistakes: tuple[str, ...] = (),
    notes: str = "",
    reflection: str = "",
    metadata: dict[str, Any] | None = None,
) -> TradeReviewV1:
    return _executed_review(
        review_mode=TradeReviewMode.PAPER_TRADE,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        decision=decision,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        execution_attribution=execution_attribution,
        execution_decision_trace_id=execution_decision_trace_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        preview_refs=preview_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=metadata,
    )


def build_live_trade_review(
    *,
    opportunity_id: str | None,
    strategy_id: str | None,
    decision: str,
    decision_time_ns: int,
    created_at_ns: int,
    execution_attribution: TradeExecutionAttribution,
    execution_decision_trace_id: str | None = None,
    evidence_snapshot_refs: tuple[ContractReference, ...] = (),
    preview_refs: tuple[ContractReference, ...] = (),
    contradictions: tuple[str, ...] = (),
    risk_snapshot: dict[str, Any] | None = None,
    ftep_campaign: str | None = None,
    ftep_session_id: str | None = None,
    tags: tuple[str, ...] = (),
    mistakes: tuple[str, ...] = (),
    notes: str = "",
    reflection: str = "",
    metadata: dict[str, Any] | None = None,
) -> TradeReviewV1:
    return _executed_review(
        review_mode=TradeReviewMode.LIVE_TRADE,
        opportunity_id=opportunity_id,
        strategy_id=strategy_id,
        decision=decision,
        decision_time_ns=decision_time_ns,
        created_at_ns=created_at_ns,
        execution_attribution=execution_attribution,
        execution_decision_trace_id=execution_decision_trace_id,
        evidence_snapshot_refs=evidence_snapshot_refs,
        preview_refs=preview_refs,
        contradictions=contradictions,
        risk_snapshot=risk_snapshot,
        ftep_campaign=ftep_campaign,
        ftep_session_id=ftep_session_id,
        tags=tags,
        mistakes=mistakes,
        notes=notes,
        reflection=reflection,
        metadata=metadata,
    )


__all__ = [
    "build_live_trade_review",
    "build_paper_trade_review",
    "build_rejected_opportunity_review",
    "build_watched_opportunity_review",
]
