"""XA-01 versioned enumerations."""

from __future__ import annotations

from enum import StrEnum


class XaAssetClass(StrEnum):
    EQUITY = "EQUITY"
    ETF_FUND = "ETF_FUND"
    FUTURE = "FUTURE"
    OPTION = "OPTION"
    SOVEREIGN_DEBT = "SOVEREIGN_DEBT"
    COMMODITY = "COMMODITY"
    FX_PAIR = "FX_PAIR"
    CURRENCY = "CURRENCY"
    INDEX_BENCHMARK = "INDEX_BENCHMARK"


class InstrumentKind(StrEnum):
    TRADABLE_SECURITY = "TRADABLE_SECURITY"
    COMMODITY_ECONOMIC = "COMMODITY_ECONOMIC"
    FUTURE_FAMILY = "FUTURE_FAMILY"
    FUTURE_CONTRACT = "FUTURE_CONTRACT"
    OPTION_CONTRACT = "OPTION_CONTRACT"
    SOVEREIGN_SECURITY = "SOVEREIGN_SECURITY"
    CURRENCY_UNIT = "CURRENCY_UNIT"
    FX_PAIR = "FX_PAIR"
    INDEX_BENCHMARK = "INDEX_BENCHMARK"


class AnalyticalDomain(StrEnum):
    EQUITY = "EQUITY"
    COMMODITY = "COMMODITY"
    MONETARY_RESERVE = "MONETARY_RESERVE"
    RATES = "RATES"
    SOVEREIGN = "SOVEREIGN"
    MACRO = "MACRO"
    FX = "FX"
    DERIVATIVES = "DERIVATIVES"
    SAFE_HAVEN = "SAFE_HAVEN"


class ExternalIdentifierType(StrEnum):
    PROVIDER_SYMBOL = "PROVIDER_SYMBOL"
    EXCHANGE_SYMBOL = "EXCHANGE_SYMBOL"
    TICKER = "TICKER"
    CUSIP = "CUSIP"
    ISIN = "ISIN"
    VENDOR_ID = "VENDOR_ID"
    DISPLAY_TICKER = "DISPLAY_TICKER"


class RelationshipType(StrEnum):
    UNDERLYING = "UNDERLYING"
    CONTRACT_ROOT = "CONTRACT_ROOT"
    DENOMINATED_IN = "DENOMINATED_IN"
    BENCHMARK_OF = "BENCHMARK_OF"


class AliasResolutionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"


class PriceUnitKind(StrEnum):
    CURRENCY_PER_SHARE = "CURRENCY_PER_SHARE"
    CURRENCY_PER_CONTRACT = "CURRENCY_PER_CONTRACT"
    INDEX_POINTS = "INDEX_POINTS"
    FX_PAIR_QUOTE = "FX_PAIR_QUOTE"
    YIELD_RATE = "YIELD_RATE"
    COMMODITY_UNIT = "COMMODITY_UNIT"


SCHEMA_VERSION = 1
IDENTITY_PROFILE = "imp-xa01-instrument-identity-v1"
