"""Inspectable inference error taxonomy."""

from __future__ import annotations

from enum import StrEnum


class InferenceErrorCode(StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    UNOBSERVABLE_EVENT = "UNOBSERVABLE_EVENT"
    PROMPT_CONFIG_INVALID = "PROMPT_CONFIG_INVALID"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_AUTH_FAILURE = "PROVIDER_AUTH_FAILURE"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT"
    PROVIDER_RESPONSE_MALFORMED = "PROVIDER_RESPONSE_MALFORMED"
    OUTPUT_SCHEMA_INVALID = "OUTPUT_SCHEMA_INVALID"
    INFERENCE_UNAVAILABLE = "INFERENCE_UNAVAILABLE"


__all__ = ["InferenceErrorCode"]
