"""Cross-build contract and authority inventory (BUILD 25)."""

from __future__ import annotations

from typing import Any

from ..contracts.common import INTELLIGENCE_SCHEMA_VERSION
from .identity import derive_contract_inventory_hash

# Canonical durable contracts discovered from repository truth.
CONTRACT_INVENTORY: dict[str, dict[str, Any]] = {
    "EventV1": {
        "module": "market_platform_foundation.intelligence.contracts.event",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_event_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "events",
        "ttl": False,
        "authority_build": 1,
    },
    "SnapshotV1": {
        "module": "market_platform_foundation.intelligence.contracts.snapshot",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_snapshot_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "snapshots",
        "ttl": False,
        "authority_build": 4,
    },
    "SignalV1": {
        "module": "market_platform_foundation.intelligence.contracts.signal",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_signal_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "signals",
        "ttl": False,
        "authority_build": 6,
    },
    "EvidenceV1": {
        "module": "market_platform_foundation.intelligence.contracts.evidence",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_evidence_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "evidence",
        "ttl": False,
        "authority_build": 12,
    },
    "HypothesisV1": {
        "module": "market_platform_foundation.intelligence.contracts.hypothesis",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_hypothesis_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "hypotheses",
        "ttl": False,
        "authority_build": 13,
    },
    "ForecastV1": {
        "module": "market_platform_foundation.intelligence.contracts.forecast",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_forecast_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "forecasts",
        "ttl": False,
        "authority_build": 14,
    },
    "PredictionLedgerEntryV1": {
        "module": "market_platform_foundation.intelligence.contracts.prediction_ledger",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_prediction_ledger_entry_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "prediction_ledger",
        "ttl": False,
        "authority_build": 15,
    },
    "OutcomeV1": {
        "module": "market_platform_foundation.intelligence.contracts.outcome",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_outcome_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "outcomes",
        "ttl": False,
        "authority_build": 15,
    },
    "EvaluationReportV1": {
        "module": "market_platform_foundation.intelligence.evaluation.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_evaluation_report_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "evaluation_reports",
        "ttl": False,
        "authority_build": 16,
    },
    "ResearchFindingV1": {
        "module": "market_platform_foundation.intelligence.research_experiments.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_research_finding_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "research_findings",
        "ttl": False,
        "authority_build": 17,
    },
    "ExperimentManifestV1": {
        "module": "market_platform_foundation.intelligence.research_experiments.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_experiment_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "experiment_manifests",
        "ttl": False,
        "authority_build": 17,
    },
    "TrainingDatasetManifestV1": {
        "module": "market_platform_foundation.intelligence.training.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_training_dataset_manifest_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "training_dataset_manifests",
        "ttl": False,
        "authority_build": 18,
    },
    "CandidateArtifactV1": {
        "module": "market_platform_foundation.intelligence.training.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_candidate_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "candidate_artifacts",
        "ttl": False,
        "authority_build": 18,
    },
    "ValidationPlanV1": {
        "module": "market_platform_foundation.intelligence.validation.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_validation_plan_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "validation_plans",
        "ttl": False,
        "authority_build": 19,
    },
    "ValidationReportV1": {
        "module": "market_platform_foundation.intelligence.validation.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_validation_report_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "validation_reports",
        "ttl": False,
        "authority_build": 19,
    },
    "PromotionDecisionV1": {
        "module": "market_platform_foundation.intelligence.promotion.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_promotion_decision_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "promotion_decisions",
        "ttl": False,
        "authority_build": 20,
    },
    "ChampionAssignmentV1": {
        "module": "market_platform_foundation.intelligence.promotion.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_champion_assignment_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "champion_assignments",
        "ttl": False,
        "authority_build": 20,
    },
    "OpportunityV1": {
        "module": "market_platform_foundation.intelligence.contracts.opportunity",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_opportunity_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "opportunities",
        "ttl": False,
        "authority_build": 21,
    },
    "TradeProposalV1": {
        "module": "market_platform_foundation.intelligence.contracts.trade_proposal",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_trade_proposal_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "trade_proposals",
        "ttl": False,
        "authority_build": 22,
    },
    "RiskDecisionV1": {
        "module": "market_platform_foundation.intelligence.execution.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_risk_decision_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "risk_decisions",
        "ttl": False,
        "authority_build": 22,
    },
    "RuntimeActivationV1": {
        "module": "market_platform_foundation.intelligence.governance.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_runtime_activation_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "runtime_activations",
        "ttl": False,
        "authority_build": 23,
    },
    "ResearchTriggerV1": {
        "module": "market_platform_foundation.intelligence.adaptation.types",
        "schema_version": INTELLIGENCE_SCHEMA_VERSION,
        "identity_algorithm": "derive_research_trigger_id",
        "strict_serialization": True,
        "unknown_key_behavior": "reject",
        "persistence_collection": "research_triggers",
        "ttl": False,
        "authority_build": 24,
    },
}

BUILD_INVENTORY: dict[int, dict[str, Any]] = {
    1: {
        "subsystem": "normalization, temporal integrity, contracts",
        "primary_modules": ["normalization", "contracts", "temporal"],
        "canonical_artifacts": ["EventV1"],
        "tests": ["test_normalization", "test_temporal_integrity", "test_intelligence_contracts"],
    },
    2: {
        "subsystem": "temporal eligibility authority",
        "primary_modules": ["temporal"],
        "canonical_artifacts": [],
        "tests": ["test_temporal_integrity"],
    },
    4: {
        "subsystem": "quality authority, persistence, snapshots",
        "primary_modules": ["quality", "persistence", "snapshots"],
        "canonical_artifacts": ["SnapshotV1"],
        "tests": ["test_quality_engine", "test_snapshot_engine", "test_persistence_conformance"],
    },
    6: {
        "subsystem": "signal authority",
        "primary_modules": ["signals"],
        "canonical_artifacts": ["SignalV1"],
        "tests": ["test_signal_engine"],
    },
    7: {
        "subsystem": "replay runtime",
        "primary_modules": ["replay"],
        "canonical_artifacts": [],
        "tests": ["test_replay_faults", "test_replay_integration"],
    },
    8: {
        "subsystem": "event detection",
        "primary_modules": ["routing"],
        "canonical_artifacts": ["DetectionV1"],
        "tests": ["test_event_detector"],
    },
    9: {
        "subsystem": "smart router",
        "primary_modules": ["routing"],
        "canonical_artifacts": ["RoutingDecisionV1"],
        "tests": ["test_smart_router"],
    },
    10: {
        "subsystem": "inference scheduler",
        "primary_modules": ["scheduling"],
        "canonical_artifacts": ["InferenceJobV1"],
        "tests": ["test_inference_scheduler"],
    },
    11: {
        "subsystem": "microstructure specialist",
        "primary_modules": ["specialists"],
        "canonical_artifacts": [],
        "tests": ["test_microstructure_specialist"],
    },
    12: {
        "subsystem": "blind council blackboard",
        "primary_modules": ["council"],
        "canonical_artifacts": ["EvidenceV1"],
        "tests": ["test_council_blind_barrier"],
    },
    13: {
        "subsystem": "composite hypothesis engine",
        "primary_modules": ["hypotheses"],
        "canonical_artifacts": ["HypothesisV1"],
        "tests": ["test_short_squeeze_hypothesis"],
    },
    14: {
        "subsystem": "fusion calibration uncertainty",
        "primary_modules": ["fusion", "baselines"],
        "canonical_artifacts": ["ForecastV1"],
        "tests": ["test_fusion_manifest", "test_uncertainty"],
    },
    15: {
        "subsystem": "prediction ledger outcome settlement",
        "primary_modules": ["outcomes"],
        "canonical_artifacts": ["PredictionLedgerEntryV1", "OutcomeV1"],
        "tests": ["test_prediction_ledger", "test_outcome_settlement"],
    },
    16: {
        "subsystem": "evaluation diagnostics",
        "primary_modules": ["evaluation"],
        "canonical_artifacts": ["EvaluationReportV1"],
        "tests": ["test_evaluation_diagnostics"],
    },
    17: {
        "subsystem": "research experiments",
        "primary_modules": ["research_experiments"],
        "canonical_artifacts": ["ResearchFindingV1", "ExperimentManifestV1"],
        "tests": ["test_research_experiments"],
    },
    18: {
        "subsystem": "training distillation factory",
        "primary_modules": ["training"],
        "canonical_artifacts": ["TrainingDatasetManifestV1", "CandidateArtifactV1"],
        "tests": ["test_training_factory"],
    },
    19: {
        "subsystem": "independent validation temporal firewall",
        "primary_modules": ["validation"],
        "canonical_artifacts": ["ValidationPlanV1", "ValidationReportV1"],
        "tests": ["test_validation_temporal_firewall"],
    },
    20: {
        "subsystem": "champion challenger promotion",
        "primary_modules": ["promotion"],
        "canonical_artifacts": ["PromotionDecisionV1", "ChampionAssignmentV1"],
        "tests": ["test_promotion_governance"],
    },
    21: {
        "subsystem": "governed opportunity engine",
        "primary_modules": ["opportunity"],
        "canonical_artifacts": ["OpportunityV1"],
        "tests": ["test_opportunity_governance"],
    },
    22: {
        "subsystem": "deterministic paper execution risk",
        "primary_modules": ["execution"],
        "canonical_artifacts": ["TradeProposalV1", "RiskDecisionV1"],
        "tests": ["test_paper_execution_governance"],
    },
    23: {
        "subsystem": "runtime governance monitoring rollback",
        "primary_modules": ["governance"],
        "canonical_artifacts": ["RuntimeActivationV1"],
        "tests": ["test_governance_governance"],
    },
    24: {
        "subsystem": "controlled adaptation research re-entry",
        "primary_modules": ["adaptation"],
        "canonical_artifacts": ["ResearchTriggerV1"],
        "tests": ["test_adaptation_controlled"],
    },
}

AUTHORITY_GRAPH: dict[str, dict[str, Any]] = {
    "temporal": {"build": 2, "module": "temporal", "authority": "point-in-time eligibility"},
    "quality": {"build": 4, "module": "quality", "authority": "data quality and capability"},
    "signals": {"build": 6, "module": "signals", "authority": "signal computation"},
    "forecast": {"build": 14, "module": "fusion", "authority": "calibrated forecast and uncertainty"},
    "settlement": {"build": 15, "module": "outcomes", "authority": "outcome settlement"},
    "evaluation": {"build": 16, "module": "evaluation", "authority": "evaluation metrics"},
    "research": {"build": 17, "module": "research_experiments", "authority": "research hypotheses and experiments"},
    "training": {"build": 18, "module": "training", "authority": "candidate generation"},
    "validation": {"build": 19, "module": "validation", "authority": "independent validation"},
    "promotion": {"build": 20, "module": "promotion", "authority": "champion promotion"},
    "opportunity": {"build": 21, "module": "opportunity", "authority": "governed opportunity"},
    "risk_paper": {"build": 22, "module": "execution", "authority": "deterministic risk and paper execution"},
    "runtime_governance": {"build": 23, "module": "governance", "authority": "runtime activation and rollback"},
    "adaptation": {"build": 24, "module": "adaptation", "authority": "controlled research re-entry"},
}

FORBIDDEN_AUTHORITY_PATHS: tuple[tuple[str, str], ...] = (
    ("signal", "order"),
    ("forecast", "order"),
    ("forecast", "trade_proposal"),
    ("outcome", "model_update"),
    ("drift", "model_fit"),
    ("monitoring", "champion"),
    ("research_trigger", "training"),
    ("candidate", "runtime_activation"),
    ("validation", "runtime_activation"),
    ("opportunity", "broker"),
    ("llm", "order"),
)

LINEAGE_EDGES: tuple[tuple[str, str, str], ...] = (
    ("EventV1", "SnapshotV1", "source_event_refs"),
    ("SnapshotV1", "SignalV1", "snapshot_ref"),
    ("SignalV1", "DetectionV1", "signal_refs"),
    ("DetectionV1", "RoutingDecisionV1", "detection_ref"),
    ("RoutingDecisionV1", "InferenceJobV1", "routing_decision_ref"),
    ("InferenceJobV1", "EvidenceV1", "job_ref"),
    ("EvidenceV1", "HypothesisV1", "evidence_refs"),
    ("HypothesisV1", "ForecastV1", "hypothesis_ref"),
    ("ForecastV1", "PredictionLedgerEntryV1", "forecast_ref"),
    ("PredictionLedgerEntryV1", "OutcomeV1", "ledger_entry_ref"),
    ("OutcomeV1", "EvaluationReportV1", "outcome_refs"),
    ("EvaluationReportV1", "ResearchFindingV1", "evaluation_report_ref"),
    ("ResearchFindingV1", "ExperimentManifestV1", "research_hypothesis_id"),
    ("ExperimentManifestV1", "TrainingDatasetManifestV1", "experiment_id"),
    ("TrainingDatasetManifestV1", "CandidateArtifactV1", "training_dataset_ref"),
    ("CandidateArtifactV1", "ValidationReportV1", "candidate_ref"),
    ("ValidationReportV1", "PromotionDecisionV1", "validation_report_ref"),
    ("PromotionDecisionV1", "ChampionAssignmentV1", "promotion_decision_ref"),
    ("ChampionAssignmentV1", "RuntimeActivationV1", "champion_assignment_id"),
    ("ChampionAssignmentV1", "ForecastV1", "champion_assignment_ref"),
    ("ForecastV1", "OpportunityV1", "forecast_ref"),
    ("OpportunityV1", "TradeProposalV1", "opportunity_ref"),
    ("TradeProposalV1", "RiskDecisionV1", "trade_proposal_ref"),
    ("RuntimeActivationV1", "OpportunityV1", "runtime_activation_ref"),
    ("DriftAssessmentV1", "ResearchTriggerV1", "source_evidence_refs"),
    ("ResearchTriggerV1", "ResearchFindingV1", "research_trigger_id"),
)


def contract_inventory_hash() -> str:
    return derive_contract_inventory_hash(CONTRACT_INVENTORY)


def build_inventory_summary() -> dict[str, Any]:
    return {
        "contract_count": len(CONTRACT_INVENTORY),
        "build_count": len(BUILD_INVENTORY),
        "authority_count": len(AUTHORITY_GRAPH),
        "lineage_edge_count": len(LINEAGE_EDGES),
        "forbidden_path_count": len(FORBIDDEN_AUTHORITY_PATHS),
    }
