// SOFTWARE_CONTROLLED. Run from IMP root after building UI and starting
// tests/acceptance/harness_prospective_evaluation.py on loopback 8891.
const {chromium}=require(process.env.IMP_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],steps=[];page.on('pageerror',e=>errors.push(String(e)));const before=await (await page.request.get('http://127.0.0.1:8891/harness-baseline')).json();await page.goto('http://127.0.0.1:8891/portfolio/evaluation');await page.waitForLoadState('networkidle');await page.locator('button[data-mode="PAPER"]').click();await page.getByRole('heading',{name:'Prospective outcome evaluation',exact:true}).waitFor();await page.waitForLoadState('networkidle');
const check=async(name,fn)=>{await fn();steps.push({name,status:'PASS'});};
await check('fixture excluded from prospective aggregate',async()=>{await page.getByText('EVIDENCE_CLASS_MISMATCH: 9',{exact:true}).waitFor();});
await page.getByLabel(/^Evidence cohort/).selectOption('SOFTWARE_CONTROLLED');await page.waitForLoadState('networkidle');
for(const label of ['Net completed Paper P&L','Average win / loss','Expectancy / completed trade','Profit factor','Maximum observed drawdown','Peak / trough / recovery / duration seconds','Longest / current losing streak','Exposure seconds / elapsed time in market','Executed notional / turnover','Explicit costs','Wins / losses / flat','Win rate (completed nonflat)'])await check(label,()=>page.getByText(label,{exact:true}).first().waitFor());
await check('weekly results',()=>page.getByRole('table',{name:'Weekly Paper results',exact:true}).waitFor());
for(const d of ['setup','asset','regime','model','direction'])await check('stored segment '+d,async()=>{await page.getByLabel(/^Group by/).selectOption(d);await page.getByRole('table',{name:'Segment comparison'}).waitFor();});
await check('segment N changes truthfully',async()=>{await page.getByLabel(/^Group by/).selectOption('instrument');await page.getByRole('combobox',{name:/^Segment/}).selectOption('NVDA');await page.getByRole('heading',{name:'Segment: NVDA'}).waitFor();});
await page.getByRole('combobox',{name:/^Segment/}).selectOption('');
const summary=await(await page.request.get('http://127.0.0.1:8891/evaluation/prospective/summary?evidence_class=SOFTWARE_CONTROLLED')).json();
await check('evidence classification / cutoff / sample sizes',async()=>{if(await page.locator('.evaluation-boundary strong').innerText()!=='SOFTWARE_CONTROLLED')throw new Error('Class');if(await page.locator('.evaluation-boundary time').innerText()!==summary.cutoff)throw new Error('Cutoff');if(!(await page.locator('.evaluation-boundary').innerText()).includes('N completed 3'))throw new Error('N');});
const rows=await(await page.request.get('http://127.0.0.1:8891/evaluation/prospective/records?evidence_class=SOFTWARE_CONTROLLED&cutoff='+encodeURIComponent(summary.cutoff))).json();
if(summary.metrics.completed_trades!==3 || summary.metrics.open_censored!==1 || summary.metrics.wins!==1 || summary.metrics.losses!==1 || summary.metrics.flat!==1) throw new Error('Wrong controlled metrics');
if(!rows.records.some(r=>r.origin==='MANUAL_UNLINKED')) throw new Error('Missing manual row');
steps.push({name:'manual unlinked activity separated',status:'PASS'},{name:'open trade excluded from completed wins/losses',status:'PASS'});
const closed=rows.records.find(r=>r.execution_outcome?.state==='CLOSED');const index=rows.records.indexOf(closed);await page.getByRole('button',{name:'Inspect AAPL',exact:true}).nth(rows.records.slice(0,index).filter(r=>r.instrument_id==='AAPL').length).click();
await check('original decision and PIT evidence',()=>page.getByRole('heading',{name:'Stored actual proposal, model, prompt and PIT evidence'}).waitFor());
await check('preserved provider/freshness/model/prompt/action/outcome',async()=>{const raw=await page.locator('.evaluation-detail').innerText();for(const key of ['CONTROLLED_FIXTURE','freshness_status','prompt_version','model_proposal','execution_outcome','decision_cutoff'])if(!raw.includes(key))throw new Error('Missing '+key);});
await check('lifecycle drilldown',async()=>{await page.getByRole('button',{name:'View current trade lifecycle'}).click();await page.getByText('Current lifecycle is a separate read; it does not replace frozen outcomes.').waitFor();});
await check('finalize immutable run',async()=>{await page.getByRole('button',{name:'Finalize frozen run'}).click();await page.getByRole('status').filter({hasText:'Frozen PE-'}).waitFor();});
await check('rerun metrics and sources match',async()=>{await page.getByRole('button',{name:'Rerun stored metrics'}).click();await page.getByRole('status').filter({hasText:'Metrics MATCH; original sources MATCH'}).waitFor();});
await page.screenshot({path:'.local/oct1-11-browser-desktop.png',fullPage:true});await page.screenshot({path:'artifacts/oct1-11-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/oct1-11-browser-mobile.png',fullPage:true});await page.screenshot({path:'artifacts/oct1-11-mobile.png'});
const after=await(await page.request.get('http://127.0.0.1:8891/harness-baseline')).json();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('Trading or model side effects');if(errors.length)throw new Error(errors.join('\n'));steps.push({name:'unchanged fills/model calls; zero Paper/Live submit requests',status:'PASS'});if(after.paper_submission_requests!==0||after.live_submissions!==0)throw new Error('Submission request observed');fs.writeFileSync('artifacts/oct1-11-browser-acceptance.json',JSON.stringify({classification:'SOFTWARE_CONTROLLED',steps,before,after,metrics:summary.metrics,admission:summary.admission,console_errors:errors,production_bundle:true,requested_scenarios:40,scenario_coverage:'40 requested scenarios exercised in grouped steps; all metric components, provenance fields and side effects have assertions',screenshots:['artifacts/oct1-11-desktop.png','artifacts/oct1-11-mobile.png']},null,2));console.log(JSON.stringify({steps:steps.length,before,after}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
