/** Test fixture: an experiment-account `/paper/portfolio` payload (AAPL marked, NVDA configurable). */
export function experimentPortfolio(options: { nvdaMark?: number | null; nvdaQuality?: string; quality?: string } = {}) {
  const nvdaMark = options.nvdaMark === undefined ? 23600 : options.nvdaMark;
  const marked = nvdaMark !== null;
  const quality = options.quality ?? (marked ? "CURRENT" : "PARTIAL");
  const cash = 7_920_000;
  const positionValue = marked ? 60 * 15500 + 50 * nvdaMark : null;
  const equity = positionValue === null ? null : cash + positionValue;
  return {
    as_of_context: {
      mode: "PAPER",
      as_of_time: "2026-10-06T18:00:00Z",
      timezone: "America/New_York",
      data_mode: "LIVE_OBSERVATIONAL",
      execution_mode: "INTERNAL_SIMULATION",
      execution_authority: "PAPER_ONLY",
    },
    authority_boundary: "PAPER_OBSERVABILITY",
    account: {
      paper_account_id: "ACCT1234567890ABCDEF",
      session_id: "sess",
      currency: "USD",
      cash_display: "79200",
      cash_minor: cash,
      buying_power_minor: cash,
      initial_cash_minor: 10_000_000,
      realized_pnl_display: "200",
      realized_pnl_minor: 20_000,
      data_mode: "LIVE_OBSERVATIONAL",
      data_provider: "MOOMOO",
      execution_mode: "INTERNAL_SIMULATION",
      execution_authority: "PAPER_ONLY",
      execution_provider: "INTERNAL",
    },
    positions: [
      {
        instrument_id: "AAPL",
        symbol: "AAPL",
        quantity: 60,
        side: "LONG",
        average_fill_minor: 15000,
        cost_basis_minor: 900_000,
        first_entry_time_ns: 1791309918000000000,
        mark_minor: 15500 as number | null,
        mark_provider: "MOOMOO",
        mark_quality: "PASS",
        mark_as_of_ns: 1791309978000000000 as number | null,
        market_value_minor: 930_000 as number | null,
        unrealized_pnl_minor: 30_000 as number | null,
      },
      {
        instrument_id: "NVDA",
        symbol: "NVDA",
        quantity: 50,
        side: "LONG",
        average_fill_minor: 24000,
        cost_basis_minor: 1_200_000,
        first_entry_time_ns: 1791309928000000000,
        mark_minor: nvdaMark,
        mark_provider: marked ? "MOOMOO" : "MARK_UNAVAILABLE",
        mark_quality: marked ? (options.nvdaQuality ?? "PASS") : "UNAVAILABLE",
        mark_as_of_ns: marked ? 1791309978000000000 : null,
        market_value_minor: marked ? 50 * nvdaMark : null,
        unrealized_pnl_minor: marked ? 50 * nvdaMark - 1_200_000 : null,
      },
    ],
    orders: [],
    fills: [],
    risk: {
      kill_switch_active: false,
      open_order_count: 0,
      reconciliation_status: "INTERNAL_AUTHORITATIVE",
      limits: { max_open_orders: 3, max_order_shares: 100, max_position_shares: 500 },
    },
    data_health: { state: "PASS", detail: "controlled" },
    active_instrument: "AAPL",
    experiment: {
      schema_version: "paper-portfolio-experiment/1.0.0",
      experiment_id: "PPE-TEST0001",
      name: "OCT1-09 live-market Paper experiment",
      status: "ACTIVE",
      paper_account_id: "ACCT1234567890ABCDEF",
      paper_session_id: "sess",
      initial_capital_minor: 10_000_000,
      currency: "USD",
      capital_kind: "SIMULATED",
      live_capital: false,
      created_at_ns: 1791309918000000000,
      ended_at_ns: null,
      data_mode: "LIVE_OBSERVATIONAL",
      data_providers: ["MOOMOO"],
      execution_mode: "INTERNAL_SIMULATION",
      execution_provider: "INTERNAL",
      evidence_class: "PROSPECTIVE_PAPER_WITH_LIVE_OBSERVATIONAL_DATA",
      bound_to_running_account: true,
      closing: null,
    },
    valuation: {
      quality,
      currency: "USD",
      initial_capital_minor: 10_000_000,
      cash_minor: cash,
      reserved_cash_minor: 0,
      buying_power_minor: cash,
      buying_power_basis: "CASH_LESS_WORKING_ORDER_RESERVATIONS_NO_LEVERAGE",
      position_value_minor: positionValue,
      marked_position_value_minor: 930_000 + (marked ? 50 * nvdaMark : 0),
      realized_pnl_minor: 20_000,
      unrealized_pnl_minor: marked ? 30_000 + 50 * nvdaMark - 1_200_000 : null,
      equity_minor: equity,
      total_pnl_minor: equity === null ? null : equity - 10_000_000,
      return_bps: equity === null ? null : Math.trunc(((equity - 10_000_000) * 10000) / 10_000_000),
      total_commission_minor: 0,
      total_fees_minor: 0,
      open_position_count: 2,
      missing_mark_instruments: marked ? [] : ["NVDA"],
      degraded_instruments: quality === "DEGRADED" ? ["NVDA"] : [],
      valuation_cutoff_ns: 1791309988000000000,
      oldest_mark_as_of_ns: 1791309978000000000,
      newest_mark_as_of_ns: 1791309978000000000,
    },
    assumptions: {
      fill_model_registry_id: "simulation.bar_conservative",
      fill_model_version: "phase7.bar-conservative/1.1.0",
      fill_source_capability: "BAR_OHLCV_1M",
      participation_cap: "1/100",
      commission_minor_per_share: 0,
      fee_minor_per_order: 0,
      cost_policy_id: "PCP-TEST",
      slippage_model: "NOT_SEPARATELY_MODELED",
      slippage_statement: "No separate slippage term.",
      pnl_statement: "Paper P&L is accounting of simulated fills. It is not evidence of a profitable strategy.",
      fill_is_market_truth: false,
    },
    boundary: {
      capital: { kind: "SIMULATED", live_capital: false },
      execution: { mode: "INTERNAL_SIMULATION", provider: "INTERNAL", execution_authority: "PAPER_ONLY", fill_kind: "SIMULATED_FILL" },
      market_data: { mode: "LIVE_OBSERVATIONAL", provider: "MOOMOO", running_mode: "LIVE_OBSERVATIONAL", state: "AVAILABLE" },
    },
  };
}

export function experimentTrades() {
  const base = {
    order_id: "ORD",
    intent_id: "INT",
    instrument_id: "AAPL",
    symbol: "AAPL",
    commission_minor: 0,
    fees_minor: 0,
    fill_kind: "SIMULATED_FILL",
  };
  return [
    {
      ...base,
      fill_id: "F2",
      side: "SELL",
      filled_quantity: 40,
      requested_quantity: 40,
      fill_price_minor: 15500,
      fill_time_ns: 1791309978000000000,
      position_effect: "REDUCE",
      position_after: 60,
      realized_pnl_delta_minor: 20_000,
      decision_source: "MANUAL_TEST",
      decision_id: null,
      risk_decision_id: null,
      lineage_refs: [
        { kind: "PAPER_PREVIEW", id: "PRV-2" },
        { kind: "PAPER_EXPERIMENT", id: "PPE-TEST0001" },
      ],
    },
    {
      ...base,
      fill_id: "F1",
      side: "BUY",
      filled_quantity: 100,
      requested_quantity: 100,
      fill_price_minor: 15000,
      fill_time_ns: 1791309918000000000,
      position_effect: "OPEN",
      position_after: 100,
      realized_pnl_delta_minor: 0,
      decision_source: "AI_DECISION_GOVERNED",
      decision_id: "AD-1",
      risk_decision_id: "RISK-1",
      lineage_refs: [
        { kind: "ACTION_DECISION", id: "AD-1" },
        { kind: "ACTION_SNAPSHOT", id: "AS-1" },
        { kind: "CANDIDATE_RUN", id: "RUN-1" },
        { kind: "PAPER_PREVIEW", id: "PRV-1" },
      ],
    },
  ];
}
