"""Order Flow / Market Microstructure intelligence lane.

Owns observable auction mechanics and reusable microstructure evidence.
Domain engines (Short Squeeze, Options, Futures) interpret evidence — they do
not own trade classification, CVD, OFI, or book-pressure primitives.
"""

from .aggressor import classify_trade, provenance_from_quality_label
from .contracts import (
    AggressorSide,
    AggressorSource,
    BookPressureEvidence,
    ClassifiedTrade,
    CVDState,
    ForecastDirection,
    ImpactEvidence,
    ImpactRegime,
    L1QuoteState,
    ExecutionForecast,
    LiquidityEvidence,
    MetaorderFlowState,
    MetaorderPrimitive,
    MboOrder,
    MboOrderSide,
    MicrostructureCapabilityTier,
    MicrostructureForecast,
    OrderFlowEvidence,
    QueuePositionEstimate,
    QueueSnapshot,
    execution_forecast_to_dict,
    metaorder_primitive_to_dict,
    queue_snapshot_to_dict,
)
from .cvd import (
    compute_cvd_series,
    compute_cvd_state,
    cvd_acceleration,
    cvd_slope,
)
from .evidence import (
    build_execution_forecast_evidence,
    build_impact_evidence,
    build_liquidity_evidence,
    build_microstructure_forecast_evidence,
    build_order_flow_evidence,
    impact_evidence_to_dict,
    liquidity_evidence_to_dict,
    metaorder_primitive_cross_lane_evidence,
    microstructure_forecast_to_dict,
    order_flow_evidence_to_dict,
)
from .execution_forecast import (
    BOOK_MODEL_VERSION,
    DEFAULT_ORDER_QTY,
    EXECUTION_METHOD,
    EXECUTION_VERSION,
    MBO_QUEUE_MODEL_VERSION,
    QUEUE_MODEL_VERSION,
    ExecutionForecastResult,
    compute_execution_forecast,
    execution_forecast_to_dict as execution_forecast_result_to_dict,
)
from .metaorder import (
    DETECTION_METHOD,
    DETECTION_VERSION,
    classified_trades_from_bars,
    detect_metaorder_primitives,
)
from .queue import (
    QUEUE_METHOD,
    QUEUE_VERSION,
    build_queue_snapshot,
    compute_queue_imbalance_mbo,
    estimate_queue_position,
    parse_mbo_orders,
)
from .forecast import (
    CONTINUATION_THRESHOLD,
    DEFAULT_HORIZON_SECONDS,
    FORECAST_METHOD,
    FORECAST_VERSION,
    MicrostructureForecastResult,
    REVERSAL_THRESHOLD,
    compute_microstructure_forecast,
    microstructure_forecast_to_dict as microstructure_forecast_result_to_dict,
)
from .impact import (
    IMPACT_METHOD,
    IMPACT_VERSION,
    ImpactDynamicsResult,
    compute_impact_dynamics,
    impact_dynamics_to_dict,
)
from .l1 import compute_l1_state, depth_imbalance_ratio, queue_imbalance
from .liquidity import (
    LIQUIDITY_METHOD_DEPTH_DELTA,
    LIQUIDITY_VERSION,
    LiquidityDynamicsResult,
    compute_liquidity_dynamics,
    compute_trajectory_resiliency,
    liquidity_dynamics_to_dict,
    snapshot_total_depth,
)
from .ofi import (
    OFI_METHOD_BBO_DELTA,
    OFI_METHOD_MULTILEVEL_CS,
    OFIResult,
    compute_bbo_ofi,
    compute_multilevel_ofi,
    compute_ofi,
    snapshot_book_state_valid,
    snapshot_pair_book_state_valid,
    snapshot_pair_sequence_valid,
)
from .lob_baseline import (
    LOB_BASELINE_METHOD,
    LOB_BASELINE_VERSION,
    LOB_M1_METHOD,
    LobBaselineForecast,
    compute_lob_baseline_forecast,
    compute_lob_forecast_for_snapshot,
    compute_m1_cvd_baseline,
    lob_baseline_forecast_to_dict,
)
from .lob_features import FEATURE_METHOD, FEATURE_VERSION, LobFeatureVector, build_lob_feature_vector

__all__ = [
    "AggressorSide",
    "AggressorSource",
    "BookPressureEvidence",
    "ClassifiedTrade",
    "CVDState",
    "DETECTION_METHOD",
    "DETECTION_VERSION",
    "MetaorderFlowState",
    "MetaorderPrimitive",
    "MboOrder",
    "MboOrderSide",
    "MBO_QUEUE_MODEL_VERSION",
    "QUEUE_METHOD",
    "QUEUE_VERSION",
    "QueuePositionEstimate",
    "QueueSnapshot",
    "DEFAULT_ORDER_QTY",
    "EXECUTION_METHOD",
    "EXECUTION_VERSION",
    "ExecutionForecast",
    "ExecutionForecastResult",
    "QUEUE_MODEL_VERSION",
    "CONTINUATION_THRESHOLD",
    "DEFAULT_HORIZON_SECONDS",
    "ForecastDirection",
    "L1QuoteState",
    "FORECAST_METHOD",
    "FORECAST_VERSION",
    "ImpactDynamicsResult",
    "ImpactEvidence",
    "ImpactRegime",
    "IMPACT_METHOD",
    "IMPACT_VERSION",
    "LIQUIDITY_METHOD_DEPTH_DELTA",
    "LIQUIDITY_VERSION",
    "MicrostructureForecast",
    "MicrostructureForecastResult",
    "OFI_METHOD_BBO_DELTA",
    "OFI_METHOD_MULTILEVEL_CS",
    "OFIResult",
    "FEATURE_METHOD",
    "FEATURE_VERSION",
    "LOB_BASELINE_METHOD",
    "LOB_BASELINE_VERSION",
    "LOB_M1_METHOD",
    "LobBaselineForecast",
    "LobFeatureVector",
    "build_lob_feature_vector",
    "compute_lob_baseline_forecast",
    "compute_lob_forecast_for_snapshot",
    "compute_m1_cvd_baseline",
    "lob_baseline_forecast_to_dict",
    "OrderFlowQualityFlag",
    "LiquidityDynamicsResult",
    "LiquidityEvidence",
    "MicrostructureCapabilityTier",
    "OrderFlowEvidence",
    "REVERSAL_THRESHOLD",
    "build_execution_forecast_evidence",
    "build_impact_evidence",
    "build_liquidity_evidence",
    "build_microstructure_forecast_evidence",
    "build_order_flow_evidence",
    "build_queue_snapshot",
    "classified_trades_from_bars",
    "compute_queue_imbalance_mbo",
    "detect_metaorder_primitives",
    "estimate_queue_position",
    "metaorder_primitive_cross_lane_evidence",
    "metaorder_primitive_to_dict",
    "parse_mbo_orders",
    "queue_snapshot_to_dict",
    "compute_bbo_ofi",
    "compute_execution_forecast",
    "compute_impact_dynamics",
    "compute_microstructure_forecast",
    "execution_forecast_result_to_dict",
    "execution_forecast_to_dict",
    "impact_evidence_to_dict",
    "compute_liquidity_dynamics",
    "compute_multilevel_ofi",
    "compute_ofi",
    "compute_trajectory_resiliency",
    "liquidity_dynamics_to_dict",
    "liquidity_evidence_to_dict",
    "microstructure_forecast_result_to_dict",
    "microstructure_forecast_to_dict",
    "snapshot_book_state_valid",
    "snapshot_pair_book_state_valid",
    "snapshot_pair_sequence_valid",
    "snapshot_total_depth",
    "classify_trade",
    "compute_cvd_series",
    "compute_cvd_state",
    "compute_l1_state",
    "cvd_acceleration",
    "cvd_slope",
    "depth_imbalance_ratio",
    "order_flow_evidence_to_dict",
    "provenance_from_quality_label",
    "queue_imbalance",
]
