"""Bounded high-value EIA petroleum and natural-gas registry."""

from __future__ import annotations

from dataclasses import dataclass

from .contracts import (
    EnergyCommodity,
    EnergyMetricClass,
    EnergyPitConfidence,
    EnergyReleaseFamily,
)


@dataclass(frozen=True, slots=True)
class RegistryEntry:
    canonical_indicator_id: str
    commodity: EnergyCommodity
    metric_class: EnergyMetricClass
    region: str
    product: str
    unit: str
    release_family: EnergyReleaseFamily
    route: str
    frequency: str
    series: str
    data_column: str = "value"
    legacy_series_id: str = ""
    estimate_status: str = ""
    pit_confidence: EnergyPitConfidence = EnergyPitConfidence.CURRENT_HISTORY_ONLY
    notes: str = ""


PETROLEUM_ROUTE = "/v2/petroleum/sum/sndw/data"
NATURAL_GAS_ROUTE = "/v2/natural-gas/stor/wkly/data"

PETROLEUM_REGISTRY: dict[str, RegistryEntry] = {
    "COMMERCIAL_CRUDE_STOCKS": RegistryEntry(
        canonical_indicator_id="COMMERCIAL_CRUDE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCESTUS1",
        legacy_series_id="WCESTUS1",
        notes="Ending stocks excluding SPR",
    ),
    "CUSHING_CRUDE_STOCKS": RegistryEntry(
        canonical_indicator_id="CUSHING_CRUDE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="CUSHING_OK",
        product="CRUDE_OIL",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCESTP11",
        legacy_series_id="WCESTP11",
    ),
    "SPR_CRUDE_STOCKS": RegistryEntry(
        canonical_indicator_id="SPR_CRUDE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="US_TOTAL",
        product="SPR_CRUDE_OIL",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCSSTUS1",
        legacy_series_id="WCSSTUS1",
        notes="Strategic Petroleum Reserve — distinct from commercial stocks",
    ),
    "TOTAL_MOTOR_GASOLINE_STOCKS": RegistryEntry(
        canonical_indicator_id="TOTAL_MOTOR_GASOLINE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="US_TOTAL",
        product="MOTOR_GASOLINE",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WGTSTUS1",
        legacy_series_id="WGTSTUS1",
    ),
    "DISTILLATE_FUEL_STOCKS": RegistryEntry(
        canonical_indicator_id="DISTILLATE_FUEL_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="US_TOTAL",
        product="DISTILLATE",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WDISTUS1",
        legacy_series_id="WDISTUS1",
    ),
    "PROPANE_PROPYLENE_STOCKS": RegistryEntry(
        canonical_indicator_id="PROPANE_PROPYLENE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="US_TOTAL",
        product="PROPANE_PROPYLENE",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WPRSTUS1",
        legacy_series_id="WPRSTUS1",
    ),
    "CRUDE_OIL_PRODUCTION": RegistryEntry(
        canonical_indicator_id="CRUDE_OIL_PRODUCTION",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCRFPUS2",
        legacy_series_id="WCRFPUS2",
        estimate_status="WEEKLY_ESTIMATE",
        pit_confidence=EnergyPitConfidence.HISTORICAL_PIT_UNCERTAIN,
        notes="Weekly estimate; subject to re-benchmarking",
    ),
    "REFINERY_CRUDE_INPUTS": RegistryEntry(
        canonical_indicator_id="REFINERY_CRUDE_INPUTS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCRRIUS2",
        legacy_series_id="WCRRIUS2",
    ),
    "REFINERY_UTILIZATION": RegistryEntry(
        canonical_indicator_id="REFINERY_UTILIZATION",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.UTILIZATION,
        region="US_TOTAL",
        product="REFINERY",
        unit="Percent",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WPULEUS3",
        legacy_series_id="WPULEUS3",
    ),
    "CRUDE_OIL_IMPORTS": RegistryEntry(
        canonical_indicator_id="CRUDE_OIL_IMPORTS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCRIMUS2",
        legacy_series_id="WCRIMUS2",
    ),
    "CRUDE_OIL_EXPORTS": RegistryEntry(
        canonical_indicator_id="CRUDE_OIL_EXPORTS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCREXUS2",
        legacy_series_id="WCREXUS2",
    ),
    "TOTAL_PETROLEUM_EXPORTS": RegistryEntry(
        canonical_indicator_id="TOTAL_PETROLEUM_EXPORTS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="TOTAL_PETROLEUM",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WTTEXUS2",
        legacy_series_id="WTTEXUS2",
    ),
    "TOTAL_PRODUCT_SUPPLIED": RegistryEntry(
        canonical_indicator_id="TOTAL_PRODUCT_SUPPLIED",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="TOTAL_PETROLEUM",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WRPUPUS2",
        legacy_series_id="WTTUPUS2",
        notes="product_supplied approximation — not literal final demand; series migrated WTTUPUS2→WRPUPUS2 (OBSERVED 2026-08-20)",
    ),
    "GASOLINE_PRODUCT_SUPPLIED": RegistryEntry(
        canonical_indicator_id="GASOLINE_PRODUCT_SUPPLIED",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="MOTOR_GASOLINE",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WGFUPUS2",
        legacy_series_id="WGFUPUS2",
    ),
    "DISTILLATE_PRODUCT_SUPPLIED": RegistryEntry(
        canonical_indicator_id="DISTILLATE_PRODUCT_SUPPLIED",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.FLOW_RATE,
        region="US_TOTAL",
        product="DISTILLATE",
        unit="Thousand Barrels per Day",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WDIUPUS2",
        legacy_series_id="WDIUPUS2",
    ),
    "CRUDE_DAYS_OF_SUPPLY": RegistryEntry(
        canonical_indicator_id="CRUDE_DAYS_OF_SUPPLY",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.RATIO,
        region="US_TOTAL",
        product="CRUDE_OIL",
        unit="Days",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="W_EPC0_VSD_NUS_DAYS",
        legacy_series_id="WD0STUS1",
        notes="Days of supply of crude oil excluding SPR; series migrated WD0STUS1→W_EPC0_VSD_NUS_DAYS (OBSERVED 2026-08-20)",
    ),
    "PADD2_COMMERCIAL_CRUDE_STOCKS": RegistryEntry(
        canonical_indicator_id="PADD2_COMMERCIAL_CRUDE_STOCKS",
        commodity=EnergyCommodity.PETROLEUM,
        metric_class=EnergyMetricClass.STOCK,
        region="PADD_2",
        product="CRUDE_OIL",
        unit="Thousand Barrels",
        release_family=EnergyReleaseFamily.WPSR,
        route=PETROLEUM_ROUTE,
        frequency="weekly",
        series="WCESTP21",
        legacy_series_id="WCESTP21",
        notes="PADD 2 distinct from Cushing",
    ),
}

NATURAL_GAS_REGISTRY: dict[str, RegistryEntry] = {
    "LOWER48_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="LOWER48_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="LOWER48",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R48_BCF",
        legacy_series_id="NG.STOR.WKLY.SW0.R48.BCF.W",
        notes="API v2 series facet NW2_EPG0_SWO_R48_BCF (OBSERVED 2026-08-20)",
    ),
    "EAST_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="EAST_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="EAST",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R31_BCF",
        notes="duoarea R31; migrated from legacy R30 facet (OBSERVED 2026-08-20)",
    ),
    "MIDWEST_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="MIDWEST_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="MIDWEST",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R32_BCF",
        notes="duoarea R32; migrated from legacy R20 facet (OBSERVED 2026-08-20)",
    ),
    "MOUNTAIN_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="MOUNTAIN_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="MOUNTAIN",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R34_BCF",
        notes="duoarea R34; migrated from legacy R40 facet (OBSERVED 2026-08-20)",
    ),
    "PACIFIC_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="PACIFIC_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="PACIFIC",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R35_BCF",
        notes="duoarea R35; migrated from legacy R50 facet (OBSERVED 2026-08-20)",
    ),
    "SOUTH_CENTRAL_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="SOUTH_CENTRAL_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="SOUTH_CENTRAL",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SWO_R33_BCF",
        notes="duoarea R33 SWO aggregate; distinct from salt/nonsalt sub-facets (OBSERVED 2026-08-20)",
    ),
    "SOUTH_CENTRAL_SALT_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="SOUTH_CENTRAL_SALT_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="SOUTH_CENTRAL_SALT",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SSO_R33_BCF",
        notes="process SSO salt underground storage; duoarea R33 (OBSERVED 2026-08-20)",
    ),
    "SOUTH_CENTRAL_NONSALT_WORKING_GAS_STORAGE": RegistryEntry(
        canonical_indicator_id="SOUTH_CENTRAL_NONSALT_WORKING_GAS_STORAGE",
        commodity=EnergyCommodity.NATURAL_GAS,
        metric_class=EnergyMetricClass.STOCK,
        region="SOUTH_CENTRAL_NONSALT",
        product="WORKING_GAS",
        unit="Billion Cubic Feet",
        release_family=EnergyReleaseFamily.WNGSR,
        route=NATURAL_GAS_ROUTE,
        frequency="weekly",
        series="NW2_EPG0_SNO_R33_BCF",
        notes="process SNO nonsalt underground storage; duoarea R33 (OBSERVED 2026-08-20)",
    ),
}

FULL_REGISTRY: dict[str, RegistryEntry] = {**PETROLEUM_REGISTRY, **NATURAL_GAS_REGISTRY}


def lookup_canonical(canonical_indicator_id: str) -> RegistryEntry | None:
    return FULL_REGISTRY.get(canonical_indicator_id)


def registry_for_release(release_family: EnergyReleaseFamily) -> dict[str, RegistryEntry]:
    if release_family == EnergyReleaseFamily.WPSR:
        return PETROLEUM_REGISTRY
    return NATURAL_GAS_REGISTRY


__all__ = [
    "FULL_REGISTRY",
    "NATURAL_GAS_REGISTRY",
    "NATURAL_GAS_ROUTE",
    "PETROLEUM_REGISTRY",
    "PETROLEUM_ROUTE",
    "RegistryEntry",
    "lookup_canonical",
    "registry_for_release",
]
