"""Live canary package (BUILD 29 + BUILD 30 supervised operations)."""

from .authorization import (
    AUTHORIZED_STATES,
    AuthorizationError,
    authorize_canary_from_human_approval,
    consume_authorization,
    disable_authorization,
    expire_authorization,
    is_authorization_submittable,
    prepare_canary_authorization_preview,
    record_human_canary_approval,
    revoke_authorization,
    transition_authorization_state,
)
from .confirmation import ConfirmationError, build_order_confirmation_preview, confirm_order, validate_confirmation_for_intent
from .gate import evaluate_canary_live_gate
from .identity import derive_account_fingerprint, derive_preview_hash
from .incidents import (
    build_default_incident_response_policy,
    create_incident,
    incident_blocks_submits,
    record_resume_approval,
    resolve_incident,
)
from .kill_switch_store import KillSwitchStore
from .ledger import LiveExecutionLedger
from .policy import BUILD29_KNOWN_LIMITATIONS, build_default_canary_policy, effective_canary_quantity_cap, validate_policy_constraints
from .portfolio import build_live_portfolio_snapshot, is_flat_for_scope
from .program_accounting import ProgramAccounting
from .program_gate import evaluate_program_active, evaluate_session_end_gate, evaluate_session_start_gate
from .program_policy import BUILD30_KNOWN_LIMITATIONS, build_default_program_policy, validate_program_policy_constraints
from .program_report import build_program_report, build_session_report
from .program_runner import ProgramRunResult, run_mock_incident_lifecycle, run_mock_program_lifecycle
from .program_status import get_program_operational_status
from .reconciliation import PreCanaryReconciliationResult, evaluate_pre_canary_reconciliation
from .reconciliation_checkpoint import build_reconciliation_checkpoint, evaluate_checkpoint_clean
from .report import build_canary_qualification_report
from .runner import BUILD28_BRANCH, CanaryRunResult, build_canary_kill_switch_permit, run_mock_canary_lifecycle
from .serialization import canary_policy_v1_to_dict, canary_report_v1_to_dict, canary_run_v1_to_dict, preview_v1_to_dict
from .submission import MockBrokerTransport
from .types import (
    LIVE_CANARY_IMPLEMENTATION_VERSION,
    LIVE_CANARY_PROGRAM_IMPLEMENTATION_VERSION,
    LIVE_CANARY_SCHEMA_VERSION,
    DEFAULT_MAX_ORDER_COUNT,
    DEFAULT_MAX_PROGRAM_NOTIONAL_MINOR,
    DEFAULT_MAX_PROGRAM_ORDER_COUNT,
    DEFAULT_MAX_PROGRAM_SESSIONS,
    DEFAULT_MAX_SINGLE_ORDER_NOTIONAL_MINOR,
    DEFAULT_MAX_TOTAL_CANARY_NOTIONAL_MINOR,
    BrokerSubmissionReceiptV1,
    CanaryAuthorizationPreviewV1,
    CanaryDisposition,
    CanaryGovernanceState,
    HumanApprovalSource,
    HumanCanaryApprovalV1,
    IncidentAction,
    IncidentSeverity,
    IncidentState,
    IncidentType,
    LiveCanaryPolicyV1,
    LiveCanaryProgramPolicyV1,
    LiveCanaryProgramReportV1,
    LiveCanaryProgramRunV1,
    LiveCanaryQualificationReportV1,
    LiveCanaryRunV1,
    LiveCanarySessionReportV1,
    LiveExecutionIncidentV1,
    LiveFillReceiptV1,
    LiveIncidentResponsePolicyV1,
    LiveOperationalResumeApprovalV1,
    LiveOrderConfirmationV1,
    LivePortfolioSnapshotV1,
    LiveReconciliationCheckpointV1,
    ProgramDisposition,
    ProgramGovernanceState,
    SessionDisposition,
    SubmissionState,
)

__all__ = [
    "AUTHORIZED_STATES",
    "BUILD28_BRANCH",
    "BUILD29_KNOWN_LIMITATIONS",
    "BUILD30_KNOWN_LIMITATIONS",
    "DEFAULT_MAX_ORDER_COUNT",
    "DEFAULT_MAX_PROGRAM_NOTIONAL_MINOR",
    "DEFAULT_MAX_PROGRAM_ORDER_COUNT",
    "DEFAULT_MAX_PROGRAM_SESSIONS",
    "DEFAULT_MAX_SINGLE_ORDER_NOTIONAL_MINOR",
    "DEFAULT_MAX_TOTAL_CANARY_NOTIONAL_MINOR",
    "LIVE_CANARY_IMPLEMENTATION_VERSION",
    "LIVE_CANARY_PROGRAM_IMPLEMENTATION_VERSION",
    "LIVE_CANARY_SCHEMA_VERSION",
    "AuthorizationError",
    "BrokerSubmissionReceiptV1",
    "CanaryAuthorizationPreviewV1",
    "CanaryDisposition",
    "CanaryGovernanceState",
    "CanaryRunResult",
    "ConfirmationError",
    "HumanApprovalSource",
    "HumanCanaryApprovalV1",
    "IncidentAction",
    "IncidentSeverity",
    "IncidentState",
    "IncidentType",
    "LiveCanaryPolicyV1",
    "LiveCanaryProgramPolicyV1",
    "LiveCanaryProgramReportV1",
    "LiveCanaryProgramRunV1",
    "LiveCanaryQualificationReportV1",
    "LiveCanaryRunV1",
    "LiveCanarySessionReportV1",
    "LiveExecutionIncidentV1",
    "LiveExecutionLedger",
    "LiveFillReceiptV1",
    "LiveIncidentResponsePolicyV1",
    "LiveOperationalResumeApprovalV1",
    "LiveOrderConfirmationV1",
    "LivePortfolioSnapshotV1",
    "LiveReconciliationCheckpointV1",
    "MockBrokerTransport",
    "PreCanaryReconciliationResult",
    "ProgramAccounting",
    "ProgramDisposition",
    "ProgramGovernanceState",
    "ProgramRunResult",
    "SessionDisposition",
    "SubmissionState",
    "authorize_canary_from_human_approval",
    "build_canary_kill_switch_permit",
    "build_canary_qualification_report",
    "build_default_canary_policy",
    "build_default_incident_response_policy",
    "build_default_program_policy",
    "build_live_portfolio_snapshot",
    "build_order_confirmation_preview",
    "build_program_report",
    "build_reconciliation_checkpoint",
    "build_session_report",
    "canary_policy_v1_to_dict",
    "canary_report_v1_to_dict",
    "canary_run_v1_to_dict",
    "confirm_order",
    "consume_authorization",
    "create_incident",
    "derive_account_fingerprint",
    "derive_preview_hash",
    "disable_authorization",
    "effective_canary_quantity_cap",
    "evaluate_canary_live_gate",
    "evaluate_checkpoint_clean",
    "evaluate_pre_canary_reconciliation",
    "evaluate_program_active",
    "evaluate_session_end_gate",
    "evaluate_session_start_gate",
    "expire_authorization",
    "get_program_operational_status",
    "incident_blocks_submits",
    "is_authorization_submittable",
    "is_flat_for_scope",
    "KillSwitchStore",
    "prepare_canary_authorization_preview",
    "preview_v1_to_dict",
    "record_human_canary_approval",
    "record_resume_approval",
    "resolve_incident",
    "revoke_authorization",
    "run_mock_canary_lifecycle",
    "run_mock_incident_lifecycle",
    "run_mock_program_lifecycle",
    "transition_authorization_state",
    "validate_confirmation_for_intent",
    "validate_policy_constraints",
    "validate_program_policy_constraints",
]
