"""Champion-challenger promotion governance (BUILD 20)."""

from .complexity import (
    challenger_is_more_complex,
    complexity_order,
    required_improvement_for_complexity,
)
from .eligibility import assess_promotion_eligibility
from .engine import PromotionEngine
from .errors import PromotionError
from .identity import (
    champion_scope_identity_payload,
    derive_challenger_registration_id,
    derive_champion_assignment_id,
    derive_champion_scope_id,
    derive_eligibility_assessment_id,
    derive_lifecycle_event_id,
    derive_promotion_decision_id,
    derive_promotion_policy_id,
    derive_shadow_evidence_id,
    promotion_policy_identity_payload,
    shadow_evidence_identity_payload,
)
from .policy import build_promotion_policy
from .serialization import (
    challenger_lifecycle_event_v1_from_dict,
    challenger_lifecycle_event_v1_to_dict,
    challenger_registration_v1_from_dict,
    challenger_registration_v1_to_dict,
    champion_assignment_v1_from_dict,
    champion_assignment_v1_to_dict,
    promotion_decision_v1_from_dict,
    promotion_decision_v1_to_dict,
    promotion_eligibility_assessment_v1_from_dict,
    promotion_eligibility_assessment_v1_to_dict,
    promotion_policy_v1_from_dict,
    promotion_policy_v1_to_dict,
    shadow_evidence_manifest_v1_from_dict,
    shadow_evidence_manifest_v1_to_dict,
)
from .shadow import aggregate_shadow_metric, build_shadow_evidence_manifest, shadow_paired_deltas
from .types import (
    PROMOTION_IMPLEMENTATION_VERSION,
    ChallengerLifecycleEventV1,
    ChallengerLifecycleState,
    ChallengerRegistrationV1,
    ChampionAssignmentReason,
    ChampionAssignmentStatus,
    ChampionAssignmentV1,
    ChampionScopeV1,
    ComplexityGateResult,
    ComplexityPolicy,
    ComplexityPolicyKind,
    EligibilityDisposition,
    GuardrailGateResult,
    GuardrailRule,
    MetricDirection,
    MetricGateResult,
    PromotionDecisionKind,
    PromotionDecisionV1,
    PromotionEligibilityAssessmentV1,
    PromotionPolicyV1,
    PromotionReasonCode,
    ShadowEvidenceManifestV1,
    ShadowMatchedObservation,
    StatisticalGateResult,
    StatisticalRequirementKind,
)

__all__ = [
    "PROMOTION_IMPLEMENTATION_VERSION",
    "ChallengerLifecycleEventV1",
    "ChallengerLifecycleState",
    "ChallengerRegistrationV1",
    "ChampionAssignmentReason",
    "ChampionAssignmentStatus",
    "ChampionAssignmentV1",
    "ChampionScopeV1",
    "ComplexityGateResult",
    "ComplexityPolicy",
    "ComplexityPolicyKind",
    "EligibilityDisposition",
    "GuardrailGateResult",
    "GuardrailRule",
    "MetricDirection",
    "MetricGateResult",
    "PromotionDecisionKind",
    "PromotionDecisionV1",
    "PromotionEligibilityAssessmentV1",
    "PromotionEngine",
    "PromotionError",
    "PromotionPolicyV1",
    "PromotionReasonCode",
    "ShadowEvidenceManifestV1",
    "ShadowMatchedObservation",
    "StatisticalGateResult",
    "StatisticalRequirementKind",
    "aggregate_shadow_metric",
    "assess_promotion_eligibility",
    "build_promotion_policy",
    "build_shadow_evidence_manifest",
    "challenger_is_more_complex",
    "challenger_lifecycle_event_v1_from_dict",
    "challenger_lifecycle_event_v1_to_dict",
    "challenger_registration_v1_from_dict",
    "challenger_registration_v1_to_dict",
    "champion_assignment_v1_from_dict",
    "champion_assignment_v1_to_dict",
    "champion_scope_identity_payload",
    "complexity_order",
    "derive_challenger_registration_id",
    "derive_champion_assignment_id",
    "derive_champion_scope_id",
    "derive_eligibility_assessment_id",
    "derive_lifecycle_event_id",
    "derive_promotion_decision_id",
    "derive_promotion_policy_id",
    "derive_shadow_evidence_id",
    "promotion_decision_v1_from_dict",
    "promotion_decision_v1_to_dict",
    "promotion_eligibility_assessment_v1_from_dict",
    "promotion_eligibility_assessment_v1_to_dict",
    "promotion_policy_identity_payload",
    "promotion_policy_v1_from_dict",
    "promotion_policy_v1_to_dict",
    "required_improvement_for_complexity",
    "shadow_evidence_identity_payload",
    "shadow_evidence_manifest_v1_from_dict",
    "shadow_evidence_manifest_v1_to_dict",
    "shadow_paired_deltas",
]
