"""Options lane — IV, Greeks, surface (O2), Q inference (O3), P vs Q (O4)."""

from .dealer import (
    DEALER_VERSION,
    aggregate_dealer_exposure,
    build_dealer_snapshot,
    estimate_contract_dealer_greeks,
)
from .event_vol import (
    EVENT_VOL_METHOD,
    EVENT_VOL_VERSION,
    build_event_vol_snapshot,
    classify_event_state,
    estimate_implied_event_move,
    estimate_iv_crush,
    load_earnings_event_fixture,
)
from .edge import (
    EDGE_VERSION,
    apply_executable_edge,
    compare_physical_vs_risk_neutral,
    estimate_execution_friction,
)
from .flow import (
    FLOW_VERSION,
    abnormal_flow_vs_baseline,
    aggregate_signed_flow,
    build_flow_snapshot,
    classify_signed_flow,
)
from .greeks import bsm_greeks, GREEKS_VERSION
from .iv import bsm_price, dual_track_iv, implied_volatility, IV_SOLVER_VERSION
from .payoff import (
    PAYOFF_METHOD,
    PAYOFF_VERSION,
    OptionLeg,
    entry_cost,
    expected_pnl_under_physical_p,
    leg_to_dict,
    payoff_at_spot,
)
from .execution import (
    EXECUTION_METHOD,
    EXECUTION_VERSION,
    SIMULATOR_REGISTRY_ID,
    build_execution_snapshot,
    build_options_order_intent,
    conservative_fill_price,
    evaluate_early_exercise,
    legs_from_candidate,
    load_execution_fixture,
    process_assignment_event,
    run_options_lifecycle,
    settle_at_expiry,
    simulate_multi_leg_entry,
)
from .strategy import (
    STRATEGY_METHOD,
    STRATEGY_VERSION,
    build_candidate_legs,
    build_strategy_snapshot,
    filter_candidates_by_liquidity,
    load_strategy_optimizer_fixture,
    rank_candidates,
    select_atm_contracts,
)
from .surface import build_surface_point, build_volatility_surface
from .surface_qa import evaluate_surface_qa
from .risk_neutral import MODEL_VERSION as RISK_NEUTRAL_MODEL_VERSION, infer_risk_neutral_distribution
from .vrp import VRP_VERSION, estimate_vrp, vrp_research_snapshot

__all__ = [
    "DEALER_VERSION",
    "EDGE_VERSION",
    "EVENT_VOL_METHOD",
    "EVENT_VOL_VERSION",
    "FLOW_VERSION",
    "GREEKS_VERSION",
    "IV_SOLVER_VERSION",
    "PAYOFF_METHOD",
    "PAYOFF_VERSION",
    "RISK_NEUTRAL_MODEL_VERSION",
    "EXECUTION_METHOD",
    "EXECUTION_VERSION",
    "SIMULATOR_REGISTRY_ID",
    "STRATEGY_METHOD",
    "STRATEGY_VERSION",
    "VRP_VERSION",
    "abnormal_flow_vs_baseline",
    "aggregate_dealer_exposure",
    "aggregate_signed_flow",
    "apply_executable_edge",
    "bsm_greeks",
    "bsm_price",
    "build_candidate_legs",
    "build_dealer_snapshot",
    "build_event_vol_snapshot",
    "build_flow_snapshot",
    "build_execution_snapshot",
    "build_options_order_intent",
    "build_strategy_snapshot",
    "build_surface_point",
    "build_volatility_surface",
    "compare_physical_vs_risk_neutral",
    "classify_event_state",
    "classify_signed_flow",
    "dual_track_iv",
    "entry_cost",
    "expected_pnl_under_physical_p",
    "estimate_contract_dealer_greeks",
    "estimate_execution_friction",
    "estimate_implied_event_move",
    "estimate_iv_crush",
    "estimate_vrp",
    "conservative_fill_price",
    "evaluate_early_exercise",
    "evaluate_surface_qa",
    "filter_candidates_by_liquidity",
    "implied_volatility",
    "infer_risk_neutral_distribution",
    "leg_to_dict",
    "load_earnings_event_fixture",
    "load_execution_fixture",
    "load_strategy_optimizer_fixture",
    "legs_from_candidate",
    "payoff_at_spot",
    "process_assignment_event",
    "rank_candidates",
    "run_options_lifecycle",
    "select_atm_contracts",
    "settle_at_expiry",
    "simulate_multi_leg_entry",
    "vrp_research_snapshot",
]
