"""XA-05 versioned enumerations."""

from __future__ import annotations

from enum import StrEnum


class EpistemicClass(StrEnum):
  OBSERVED_FACT = "OBSERVED_FACT"
  REPORTED_CLAIM = "REPORTED_CLAIM"
  STATED_RATIONALE = "STATED_RATIONALE"
  INFERRED_BEHAVIOR = "INFERRED_BEHAVIOR"
  INFERRED_MOTIVE = "INFERRED_MOTIVE"
  NARRATIVE = "NARRATIVE"
  HYPOTHESIS = "HYPOTHESIS"
  MODEL_OUTPUT = "MODEL_OUTPUT"


class EvidenceAvailabilityStatus(StrEnum):
  AVAILABLE = "AVAILABLE"
  MISSING = "MISSING"
  STALE = "STALE"
  CONFLICTING = "CONFLICTING"
  INSUFFICIENT = "INSUFFICIENT"
  NOT_APPLICABLE = "NOT_APPLICABLE"


class StateDimensionId(StrEnum):
  RATES_CURVE_CONFIGURATION = "RATES_CURVE_CONFIGURATION"
  POLICY_RATE_LEVEL = "POLICY_RATE_LEVEL"
  POSITIONING_CONCENTRATION = "POSITIONING_CONCENTRATION"
  DATA_FRESHNESS = "DATA_FRESHNESS"
  CROSS_DOMAIN_PARTICIPATION = "CROSS_DOMAIN_PARTICIPATION"


SCHEMA_VERSION = 1
IDENTITY_PROFILE = "imp-xa05-strategic-state-v1"
ENGINE_PROFILE = "imp-xa05-state-engine-v1"
