"""Stable OF-01 runtime and operation error codes."""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Mapping


class OF01ErrorCode(StrEnum):
    INVALID_COMMAND = "OF01_INVALID_COMMAND"
    COMMAND_ID_CONFLICT = "OF01_COMMAND_ID_CONFLICT"
    DOMAIN_ID_CONFLICT = "OF01_DOMAIN_ID_CONFLICT"
    PRECONDITION_CHANGED = "OF01_PRECONDITION_CHANGED"
    INVALID_TRANSITION = "OF01_INVALID_TRANSITION"
    MISSING_REFERENCE = "OF01_MISSING_REFERENCE"
    UNSUPPORTED_COMMAND_SCHEMA = "OF01_UNSUPPORTED_COMMAND_SCHEMA"
    DISPOSITION_AMBIGUOUS = "OF01_DISPOSITION_AMBIGUOUS"
    SQLITE_BUSY = "OF01_SQLITE_BUSY"
    STORAGE_UNWRITABLE = "OF01_STORAGE_UNWRITABLE"
    UNSUPPORTED_FILESYSTEM = "OF01_UNSUPPORTED_FILESYSTEM"
    MULTIPLE_WRITERS = "OF01_MULTIPLE_WRITERS"
    AMBIGUOUS_COMMIT = "OF01_AMBIGUOUS_COMMIT"
    APPEND_ONLY_UPDATE_PROHIBITED = "OF01_APPEND_ONLY_UPDATE_PROHIBITED"
    APPEND_ONLY_DELETE_PROHIBITED = "OF01_APPEND_ONLY_DELETE_PROHIBITED"
    CAS_PREPARE_FAILED = "OF01_CAS_PREPARE_FAILED"
    CAS_HASH_MISMATCH = "OF01_CAS_HASH_MISMATCH"
    CAS_REFERENCED_OBJECT_MISSING = "OF01_CAS_REFERENCED_OBJECT_MISSING"
    CAS_ORPHAN_FOUND = "OF01_CAS_ORPHAN_FOUND"
    CAS_GC_AUTHORIZATION_MISMATCH = "OF01_CAS_GC_AUTHORIZATION_MISMATCH"
    INTEGRITY_FATAL = "OF01_INTEGRITY_FATAL"
    SCHEMA_UNSUPPORTED = "OF01_SCHEMA_UNSUPPORTED"
    RECORD_HASH_MISMATCH = "OF01_RECORD_HASH_MISMATCH"
    COMMIT_HASH_MISMATCH = "OF01_COMMIT_HASH_MISMATCH"
    MEMBERSHIP_MISMATCH = "OF01_MEMBERSHIP_MISMATCH"
    FOREIGN_KEY_MISMATCH = "OF01_FOREIGN_KEY_MISMATCH"
    BACKUP_INCOMPLETE = "OF01_BACKUP_INCOMPLETE"
    BACKUP_VERIFY_FAILED = "OF01_BACKUP_VERIFY_FAILED"
    RESTORE_VERIFY_FAILED = "OF01_RESTORE_VERIFY_FAILED"
    AUTHORITY_IDENTITY_MISMATCH = "OF01_AUTHORITY_IDENTITY_MISMATCH"
    ACTIVATION_PROHIBITED = "OF01_ACTIVATION_PROHIBITED"
    MIGRATION_PATH_UNSUPPORTED = "OF01_MIGRATION_PATH_UNSUPPORTED"
    MIGRATION_BACKUP_REQUIRED = "OF01_MIGRATION_BACKUP_REQUIRED"
    MIGRATION_VERIFY_FAILED = "OF01_MIGRATION_VERIFY_FAILED"
    PROJECTION_UNAVAILABLE = "OF01_PROJECTION_UNAVAILABLE"
    PROJECTION_CURSOR_INVALID = "OF01_PROJECTION_CURSOR_INVALID"
    PROJECTION_REBUILD_REQUIRED = "OF01_PROJECTION_REBUILD_REQUIRED"
    NOT_READY = "OF01_NOT_READY"
    MAINTENANCE_REQUIRED = "OF01_MAINTENANCE_REQUIRED"
    AUTHORIZATION_REQUIRED = "OF01_AUTHORIZATION_REQUIRED"
    ADMISSION_BACKPRESSURE = "OF01_ADMISSION_BACKPRESSURE"
    SHUTDOWN_IN_PROGRESS = "OF01_SHUTDOWN_IN_PROGRESS"


JsonValue = str | int | float | bool | None | list[Any] | dict[str, Any]


class OF01Error(Exception):
    code: OF01ErrorCode
    message: str
    details: Mapping[str, JsonValue]

    def __init__(
        self,
        code: OF01ErrorCode,
        message: str,
        details: Mapping[str, JsonValue],
    ) -> None:
        self.code = code
        self.message = message
        self.details = details
        super().__init__(f"{code}: {message}")

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"
