"""Backend-independent intelligence repository contract (BUILD 04.5)."""

from __future__ import annotations

from enum import StrEnum
from typing import Protocol, runtime_checkable

from ..contracts.event import EventV1
from ..contracts.detection import DetectionV1
from ..contracts.evidence import EvidenceV1
from ..contracts.forecast import ForecastV1
from ..contracts.hypothesis import HypothesisV1
from ..contracts.opportunity import OpportunityV1
from ..contracts.outcome import OutcomeV1
from ..contracts.prediction_ledger import PredictionLedgerEntryV1
from ..contracts.run_manifest import RunManifestV1
from ..contracts.signal import SignalV1
from ..contracts.snapshot import SnapshotV1
from ..contracts.routing_decision import RoutingDecisionV1
from ..contracts.inference_job import InferenceJobV1
from ..contracts.strategy_match import StrategyMatch
from ..temporal.policy import TemporalIntegrityPolicy


class RepositoryPutResult(StrEnum):
    INSERTED = "INSERTED"
    ALREADY_PRESENT = "ALREADY_PRESENT"


@runtime_checkable
class IntelligenceRepository(Protocol):
    """Typed persistence boundary for canonical intelligence records."""

    def put_event(self, event: EventV1) -> RepositoryPutResult: ...

    def get_event(self, event_id: str) -> EventV1 | None: ...

    def get_events(self, event_ids: tuple[str, ...] | list[str]) -> tuple[EventV1, ...]: ...

    def put_detection(self, detection: DetectionV1) -> RepositoryPutResult: ...

    def get_detection(self, detection_id: str) -> DetectionV1 | None: ...

    def get_detections_by_snapshot(self, snapshot_id: str) -> tuple[DetectionV1, ...]: ...

    def put_routing_decision(self, decision: RoutingDecisionV1) -> RepositoryPutResult: ...

    def get_routing_decision(self, routing_decision_id: str) -> RoutingDecisionV1 | None: ...

    def get_routes_by_detection(self, detection_id: str) -> tuple[RoutingDecisionV1, ...]: ...

    def put_inference_job(self, job: InferenceJobV1) -> RepositoryPutResult: ...

    def get_inference_job(self, job_id: str) -> InferenceJobV1 | None: ...

    def put_snapshot(self, snapshot: SnapshotV1) -> RepositoryPutResult: ...

    def get_snapshot(self, snapshot_id: str) -> SnapshotV1 | None: ...

    def put_signal(self, signal: SignalV1) -> RepositoryPutResult: ...

    def get_signal(self, signal_id: str) -> SignalV1 | None: ...

    def get_signals(self, signal_ids: tuple[str, ...] | list[str]) -> tuple[SignalV1, ...]: ...

    def put_evidence(self, evidence: EvidenceV1) -> RepositoryPutResult: ...

    def get_evidence(self, evidence_id: str) -> EvidenceV1 | None: ...

    def put_hypothesis(self, hypothesis: HypothesisV1) -> RepositoryPutResult: ...

    def get_hypothesis(self, hypothesis_id: str) -> HypothesisV1 | None: ...

    def put_forecast(self, forecast: ForecastV1) -> RepositoryPutResult: ...

    def get_forecast(self, forecast_id: str) -> ForecastV1 | None: ...

    def put_opportunity(self, opportunity: OpportunityV1) -> RepositoryPutResult: ...

    def get_opportunity(self, opportunity_id: str) -> OpportunityV1 | None: ...

    def put_allocation_decision(self, decision) -> RepositoryPutResult: ...

    def get_allocation_decision(self, allocation_decision_id: str): ...

    def get_allocation_decisions_by_set(
        self,
        decision_set_id: str,
        *,
        account_id: str | None = None,
        mode: str | None = None,
    ) -> tuple: ...

    def query_allocation_decisions(
        self,
        *,
        account_id: str | None = None,
        mode: str | None = None,
        decision_from_ns: int | None = None,
        decision_to_ns: int | None = None,
        limit: int = 1000,
    ) -> tuple: ...

    def put_strategy_match(self, match: StrategyMatch) -> RepositoryPutResult: ...

    def get_strategy_match(self, match_id: str) -> StrategyMatch | None: ...

    def put_strategy_attribution(self, attribution: StrategyAttributionV1) -> RepositoryPutResult: ...

    def get_strategy_attribution(
        self,
        attribution_id: str,
        *,
        account_id: str | None = None,
        mode: str | None = None,
        as_of_ns: int | None = None,
    ) -> StrategyAttributionV1 | None: ...

    def get_strategy_attributions_by_allocation(
        self,
        allocation_decision_id: str,
        *,
        account_id: str | None = None,
        mode: str | None = None,
        as_of_ns: int | None = None,
    ) -> tuple[StrategyAttributionV1, ...]: ...

    def put_outcome(self, outcome: OutcomeV1) -> RepositoryPutResult: ...

    def get_outcome(self, outcome_id: str) -> OutcomeV1 | None: ...

    def put_prediction_ledger_entry(self, entry: PredictionLedgerEntryV1) -> RepositoryPutResult: ...

    def get_prediction_ledger_entry(self, ledger_entry_id: str) -> PredictionLedgerEntryV1 | None: ...

    def get_prediction_ledger_entries_by_forecast(
        self, forecast_id: str
    ) -> tuple[PredictionLedgerEntryV1, ...]: ...

    def query_prediction_ledger_entries(
        self,
        *,
        decision_start_ns: int,
        decision_end_ns: int,
        mode: str | None = None,
        scenario_id: str | None = None,
        target_kind: str | None = None,
        horizon_ns: int | None = None,
        limit: int = 1000,
    ) -> tuple[PredictionLedgerEntryV1, ...]: ...

    def put_run_manifest(self, manifest: RunManifestV1) -> RepositoryPutResult: ...

    def get_run_manifest(self, run_id: str) -> RunManifestV1 | None: ...

    def query_events_as_of(
        self,
        decision_time_ns: int,
        *,
        instrument_id: str | None = None,
        event_type: str | None = None,
        limit: int = 1000,
        require_usable: bool = False,
        policy: TemporalIntegrityPolicy | None = None,
    ) -> tuple[EventV1, ...]: ...

    def iter_events_by_availability(
        self,
        *,
        start_time_ns: int,
        end_time_ns: int,
        instrument_id: str | None = None,
        event_type: str | None = None,
        provider_id: str | None = None,
        limit: int | None = None,
    ) -> tuple[EventV1, ...]: ...

    def query_signals_as_of(
        self,
        decision_time_ns: int,
        *,
        instrument_id: str | None = None,
        limit: int = 1000,
        policy: TemporalIntegrityPolicy | None = None,
    ) -> tuple[SignalV1, ...]: ...

    def get_evidence_by_snapshot(self, snapshot_id: str) -> tuple[EvidenceV1, ...]: ...

    def get_forecasts_by_instrument(
        self,
        instrument_id: str,
        *,
        decision_from_ns: int | None = None,
        decision_to_ns: int | None = None,
        limit: int = 1000,
    ) -> tuple[ForecastV1, ...]: ...

    def get_outcomes_by_forecast(self, forecast_id: str) -> tuple[OutcomeV1, ...]: ...

    def get_opportunities_by_instrument(
        self,
        instrument_id: str,
        *,
        valid_at_ns: int | None = None,
        limit: int = 1000,
    ) -> tuple[OpportunityV1, ...]: ...

    def put_research_finding(self, finding) -> RepositoryPutResult: ...

    def get_research_finding(self, finding_id: str): ...

    def put_research_hypothesis(self, hypothesis) -> RepositoryPutResult: ...

    def get_research_hypothesis(self, research_hypothesis_id: str): ...

    def query_experiment_manifests_by_hypothesis(
        self, research_hypothesis_id: str
    ) -> tuple: ...

    def put_experiment_manifest(self, manifest) -> RepositoryPutResult: ...

    def get_experiment_manifest(self, experiment_id: str): ...

    def put_research_lifecycle_event(self, event) -> RepositoryPutResult: ...

    def get_research_lifecycle_events(
        self, entity_id: str
    ) -> tuple: ...

    def put_training_dataset_manifest(self, manifest) -> RepositoryPutResult: ...

    def get_training_dataset_manifest(self, training_dataset_id: str): ...

    def put_training_run_manifest(self, run) -> RepositoryPutResult: ...

    def get_training_run_manifest(self, training_run_id: str): ...

    def put_candidate_artifact(self, candidate) -> RepositoryPutResult: ...

    def get_candidate_artifact(self, candidate_id: str): ...

    def put_distillation_dataset_manifest(self, manifest) -> RepositoryPutResult: ...

    def get_distillation_dataset_manifest(self, distillation_dataset_id: str): ...

    def put_validation_plan(self, plan) -> RepositoryPutResult: ...

    def get_validation_plan(self, validation_plan_id: str): ...

    def put_holdout_commitment(self, commitment) -> RepositoryPutResult: ...

    def get_holdout_commitment(self, holdout_commitment_id: str): ...

    def put_holdout_unlock_receipt(self, receipt) -> RepositoryPutResult: ...

    def get_holdout_unlock_receipt(self, receipt_id: str): ...

    def put_contamination_record(self, record) -> RepositoryPutResult: ...

    def get_contamination_record(self, contamination_record_id: str): ...

    def put_validation_report(self, report) -> RepositoryPutResult: ...

    def get_validation_report(self, validation_report_id: str): ...

    def put_promotion_policy(self, policy) -> RepositoryPutResult: ...

    def get_promotion_policy(self, promotion_policy_id: str): ...

    def put_promotion_eligibility_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_promotion_eligibility_assessment(self, assessment_id: str): ...

    def put_challenger_registration(self, registration) -> RepositoryPutResult: ...

    def get_challenger_registration(self, challenger_registration_id: str): ...

    def put_shadow_evidence_manifest(self, manifest) -> RepositoryPutResult: ...

    def get_shadow_evidence_manifest(self, shadow_evidence_id: str): ...

    def put_promotion_decision(self, decision) -> RepositoryPutResult: ...

    def get_promotion_decision(self, promotion_decision_id: str): ...

    def put_champion_assignment(self, assignment) -> RepositoryPutResult: ...

    def get_champion_assignment(self, assignment_id: str): ...

    def get_champion_assignments_for_scope(
        self,
        *,
        component: str,
        target_kind: str,
        horizon_ns: int,
        mode: str,
        scenario_id: str | None = None,
    ) -> tuple: ...

    def get_current_champion_assignment(
        self,
        *,
        component: str,
        target_kind: str,
        horizon_ns: int,
        mode: str,
        as_of_ns: int,
        scenario_id: str | None = None,
    ): ...

    def put_challenger_lifecycle_event(self, event) -> RepositoryPutResult: ...

    def get_challenger_lifecycle_events(self, challenger_registration_id: str) -> tuple: ...

    def put_opportunity_policy(self, policy) -> RepositoryPutResult: ...

    def get_opportunity_policy(self, opportunity_policy_id: str): ...

    def put_opportunity_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_opportunity_assessment(self, assessment_id: str): ...

    def get_opportunity_assessments_by_forecast(self, forecast_id: str) -> tuple: ...

    def put_economic_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_economic_assessment(self, assessment_id: str): ...

    def put_universal_economic_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_universal_economic_assessment(self, assessment_id: str): ...

    def put_execution_policy(self, policy) -> RepositoryPutResult: ...

    def get_execution_policy(self, execution_policy_id: str): ...

    def put_paper_portfolio_snapshot(self, snapshot) -> RepositoryPutResult: ...

    def get_paper_portfolio_snapshot(self, snapshot_id: str): ...

    def put_trade_proposal(self, proposal) -> RepositoryPutResult: ...

    def get_trade_proposal(self, proposal_id: str): ...

    def put_risk_decision(self, decision) -> RepositoryPutResult: ...

    def get_risk_decision(self, risk_decision_id: str): ...

    def put_order_ready(self, order_ready) -> RepositoryPutResult: ...

    def get_order_ready(self, order_ready_id: str): ...

    def get_order_ready_by_allocation(self, allocation_decision_id: str) -> tuple: ...

    def put_runtime_activation_policy(self, policy) -> RepositoryPutResult: ...

    def get_runtime_activation_policy(self, activation_policy_id: str): ...

    def put_runtime_activation(self, activation) -> RepositoryPutResult: ...

    def get_runtime_activation(self, activation_id: str): ...

    def get_runtime_activations_for_scope(
        self,
        *,
        component: str,
        target_kind: str,
        horizon_ns: int,
        mode: str,
        scenario_id: str | None = None,
    ) -> tuple: ...

    def get_current_runtime_activation(
        self,
        *,
        component: str,
        target_kind: str,
        horizon_ns: int,
        mode: str,
        as_of_ns: int,
        scenario_id: str | None = None,
    ): ...

    def put_drift_policy(self, policy) -> RepositoryPutResult: ...

    def get_drift_policy(self, drift_policy_id: str): ...

    def put_drift_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_drift_assessment(self, drift_assessment_id: str): ...

    def put_governance_alert(self, alert) -> RepositoryPutResult: ...

    def get_governance_alert(self, alert_id: str): ...

    def put_fail_safe_policy(self, policy) -> RepositoryPutResult: ...

    def get_fail_safe_policy(self, fail_safe_policy_id: str): ...

    def put_fail_safe_decision(self, decision) -> RepositoryPutResult: ...

    def get_fail_safe_decision(self, decision_id: str): ...

    def put_rollback_policy(self, policy) -> RepositoryPutResult: ...

    def get_rollback_policy(self, rollback_policy_id: str): ...

    def put_rollback_decision(self, decision) -> RepositoryPutResult: ...

    def get_rollback_decision(self, rollback_decision_id: str): ...

    def put_governance_event(self, event) -> RepositoryPutResult: ...

    def get_governance_event(self, event_id: str): ...

    def put_adaptation_policy(self, policy) -> RepositoryPutResult: ...

    def get_adaptation_policy(self, adaptation_policy_id: str): ...

    def put_adaptation_assessment(self, assessment) -> RepositoryPutResult: ...

    def get_adaptation_assessment(self, adaptation_assessment_id: str): ...

    def put_research_trigger(self, trigger) -> RepositoryPutResult: ...

    def get_research_trigger(self, research_trigger_id: str): ...

    def query_research_triggers_by_dedup_key(self, dedup_key: str) -> tuple: ...

    def put_adaptation_campaign(self, campaign) -> RepositoryPutResult: ...

    def get_adaptation_campaign(self, adaptation_campaign_id: str): ...

    def put_adaptation_event(self, event) -> RepositoryPutResult: ...

    def get_adaptation_event(self, event_id: str): ...

    def check_health(self) -> dict[str, object]: ...


__all__ = ["IntelligenceRepository", "RepositoryPutResult"]
