"""Weather source and PIT quality taxonomy."""

from enum import StrEnum


class WeatherQualityFlag(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    FORECAST_NOT_YET_AVAILABLE = "FORECAST_NOT_YET_AVAILABLE"
    FORECAST_ARCHIVE_GAP = "FORECAST_ARCHIVE_GAP"
    FORECAST_VINTAGE_UNAVAILABLE = "FORECAST_VINTAGE_UNAVAILABLE"
    FORECAST_AVAILABILITY_UNCERTAIN = "FORECAST_AVAILABILITY_UNCERTAIN"
    REGION_UNRESOLVED = "REGION_UNRESOLVED"
    SOURCE_REGION_MAPPING_ANOMALY = "SOURCE_REGION_MAPPING_ANOMALY"
    GRID_MAPPING_CHANGED = "GRID_MAPPING_CHANGED"
    WITHHELD = "WITHHELD"
    MISSING_VALUE = "MISSING_VALUE"
    ARCHIVE_VERSION_CHANGED = "ARCHIVE_VERSION_CHANGED"
    CLIMATOLOGY_INCOMPATIBLE = "CLIMATOLOGY_INCOMPATIBLE"
    FORECAST_REALIZATION_UNAVAILABLE = "FORECAST_REALIZATION_UNAVAILABLE"
    NDFD_DECODE_UNAVAILABLE = "NDFD_DECODE_UNAVAILABLE"
    ARCHIVE_AVAILABLE_DECODE_DEFERRED = "ARCHIVE_AVAILABLE_DECODE_DEFERRED"
    OBSERVATION_LATENCY_UNCERTAIN = "OBSERVATION_LATENCY_UNCERTAIN"


def quality_blocks_value(flags: tuple[str, ...]) -> bool:
    blocking = {
        WeatherQualityFlag.SOURCE_UNAVAILABLE.value,
        WeatherQualityFlag.WITHHELD.value,
        WeatherQualityFlag.MISSING_VALUE.value,
        WeatherQualityFlag.FORECAST_VINTAGE_UNAVAILABLE.value,
    }
    return bool(blocking.intersection(flags))


__all__ = ["WeatherQualityFlag", "quality_blocks_value"]
